[tool.poetry]
name = "apns_sdk_py"
version = "0.1.0"
description = ""
authors = ["dev <dev@qiyutech.tech>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = ">=2.24,<2.25"
aiohttp = ">=3.6,<4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
