from djangocensus.models.ContinentModel import ContinentModel
from djangocensus.models.CountryModel import CountryModel
from djangocensus.models.StateModel import StateModel
from djangocensus.models.DistrictModel import DistrictModel
from djangocensus.models.CityModel import CityModel
from djangocensus.models.VillageModel import VillageModel
from djangocensus.models.ReligiousPopulationModel import ReligiousPopulationModel
from djangocensus.models.ReligionModel import ReligionModel
from djangocensus.models.PopulationModel import PopulationModel
from djangocensus.models.LitracyModel import LitracyModel