- job:
    name: oslo.cache-functional
    parent: openstack-tox
    abstract: true
    pre-run: playbooks/tests/functional/pre.yml
    vars:
      tox_envlist: functional

- job:
    name: oslo.cache-functional-etcd3gw
    parent: oslo.cache-functional
    vars:
      tox_environment:
        PIFPAF_DAEMON: etcd
        # The next env var correspond to the functional test
        # directory to pass to STESTR_TEST_PATH
        OSLO_BACKEND: etcd3gw

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - oslo.cache-functional-etcd3gw
