
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-24T20:12:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "693d3f23ac66703c3444fefef887e3b7ad3c978a",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
