
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-21T23:13:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d63dd8a934aa7efb506f0f542fe4ddaa3218505f",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
