[tool.poetry]
name = "beet"
version = "0.0.0"
description = "A python library and toolchain for programmatic Minecraft data packs and resource packs"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/beet"
repository = "https://github.com/vberlier/beet"
documentation = "https://github.com/vberlier/beet"

readme = "README.md"

keywords = [
  "beet",
  "minecraft",
  "datapack",
  "resource-pack",
  "mcfunction"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.0.1"

[tool.poetry.scripts]
beet = "beet.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
