# Generated by Django 2.1.7 on 2020-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20200720_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfillogin',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpontofuncao',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontofuncao',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versao',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_delete_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_delete_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_edicao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_edicao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_insercao_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='origem_insercao_tipo',
            field=models.CharField(blank=True, default='USR.PROFILE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versaoitem',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
