[tool.flit.metadata]
module="citty"
author="aghast"
author-email="aghast@aghast.dev"
home-page="https://gitlab.com/aghast/citty/"
requires=[
    "docopt-ng",
]
requires-python=">=3.6"
description-file="README.md"
classifiers= [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Testing",
]

[tool.flit.metadata.requires-extra]
test = [ "pytest", ]

[tool.flit.metadata.urls]
Documentation = "https://gitlab.com/aghast/citty/-/blob/master/README.md#name"
"Source Code" = "https://gitlab.com/aghast/citty/"

[tool.flit.entrypoints.console_scripts]
citty = "citty:main"

[tool.flit.entrypoints.citty_test_funcs]
make_test = "citty:make_test"
