
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-21T17:29:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba5cf2e9ec56730e2b56c4812d3840db7e8f5036",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
