# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(848, 641)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Login)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Login)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_login = QtWidgets.QWidget()
        self.tab_login.setObjectName("tab_login")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_login)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.splitter_all = QtWidgets.QSplitter(self.tab_login)
        self.splitter_all.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_all.setObjectName("splitter_all")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_all)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vBox_left = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vBox_left.setContentsMargins(0, 0, 0, 0)
        self.vBox_left.setObjectName("vBox_left")
        self.gBox_mode = QtWidgets.QGroupBox(self.layoutWidget)
        self.gBox_mode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gBox_mode.setObjectName("gBox_mode")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gBox_mode)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_mode = QtWidgets.QLabel(self.gBox_mode)
        self.lab_mode.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lab_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_mode.setObjectName("lab_mode")
        self.horizontalLayout_2.addWidget(self.lab_mode)
        self.cBox_mode = QtWidgets.QComboBox(self.gBox_mode)
        self.cBox_mode.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cBox_mode.setObjectName("cBox_mode")
        self.cBox_mode.addItem("")
        self.cBox_mode.addItem("")
        self.horizontalLayout_2.addWidget(self.cBox_mode)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.gBox_mode)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_mf4 = QtWidgets.QWidget()
        self.page_mf4.setObjectName("page_mf4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_mf4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_mf4 = QtWidgets.QPushButton(self.page_mf4)
        self.btn_mf4.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_mf4.setFont(font)
        self.btn_mf4.setIconSize(QtCore.QSize(15, 15))
        self.btn_mf4.setAutoDefault(False)
        self.btn_mf4.setDefault(False)
        self.btn_mf4.setFlat(False)
        self.btn_mf4.setObjectName("btn_mf4")
        self.horizontalLayout_3.addWidget(self.btn_mf4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cBox_resample = QtWidgets.QCheckBox(self.page_mf4)
        self.cBox_resample.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.cBox_resample.setFont(font)
        self.cBox_resample.setChecked(True)
        self.cBox_resample.setObjectName("cBox_resample")
        self.horizontalLayout_3.addWidget(self.cBox_resample)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lab_mf4_file = QtWidgets.QLabel(self.page_mf4)
        self.lab_mf4_file.setMinimumSize(QtCore.QSize(0, 40))
        self.lab_mf4_file.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_mf4_file.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_mf4_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_mf4_file.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_mf4_file.setObjectName("lab_mf4_file")
        self.verticalLayout.addWidget(self.lab_mf4_file)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.stackedWidget.addWidget(self.page_mf4)
        self.page_a2l = QtWidgets.QWidget()
        self.page_a2l.setObjectName("page_a2l")
        self.stackedWidget.addWidget(self.page_a2l)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.vBox_left.addWidget(self.gBox_mode)
        self.gBox_search = QtWidgets.QGroupBox(self.layoutWidget)
        self.gBox_search.setObjectName("gBox_search")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.gBox_search)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hbox_search = QtWidgets.QHBoxLayout()
        self.hbox_search.setObjectName("hbox_search")
        self.horizontalLayout_5.addLayout(self.hbox_search)
        self.vBox_left.addWidget(self.gBox_search)
        self.tView_channel = QtWidgets.QTreeView(self.layoutWidget)
        self.tView_channel.setObjectName("tView_channel")
        self.vBox_left.addWidget(self.tView_channel)
        self.vbox_btn = QtWidgets.QHBoxLayout()
        self.vbox_btn.setObjectName("vbox_btn")
        self.btn_load = QtWidgets.QToolButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pho/open.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_load.setIcon(icon)
        self.btn_load.setIconSize(QtCore.QSize(32, 32))
        self.btn_load.setAutoRaise(True)
        self.btn_load.setObjectName("btn_load")
        self.vbox_btn.addWidget(self.btn_load)
        self.btn_save = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pho/save.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_save.setIcon(icon1)
        self.btn_save.setIconSize(QtCore.QSize(32, 32))
        self.btn_save.setAutoRaise(True)
        self.btn_save.setObjectName("btn_save")
        self.vbox_btn.addWidget(self.btn_save)
        self.btn_check_all = QtWidgets.QToolButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pho/check_all.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_check_all.setIcon(icon2)
        self.btn_check_all.setIconSize(QtCore.QSize(32, 32))
        self.btn_check_all.setAutoRaise(True)
        self.btn_check_all.setObjectName("btn_check_all")
        self.vbox_btn.addWidget(self.btn_check_all)
        self.btn_clear_all = QtWidgets.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pho/clear_all.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_clear_all.setIcon(icon3)
        self.btn_clear_all.setIconSize(QtCore.QSize(32, 32))
        self.btn_clear_all.setAutoRaise(True)
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.vbox_btn.addWidget(self.btn_clear_all)
        self.btn_num = QtWidgets.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pho/num.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_num.setIcon(icon4)
        self.btn_num.setIconSize(QtCore.QSize(32, 32))
        self.btn_num.setAutoRaise(True)
        self.btn_num.setObjectName("btn_num")
        self.vbox_btn.addWidget(self.btn_num)
        self.btn_yt = QtWidgets.QToolButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pho/yt.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_yt.setIcon(icon5)
        self.btn_yt.setIconSize(QtCore.QSize(32, 32))
        self.btn_yt.setAutoRaise(True)
        self.btn_yt.setObjectName("btn_yt")
        self.vbox_btn.addWidget(self.btn_yt)
        self.btn_birdview = QtWidgets.QToolButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pho/birdview.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btn_birdview.setIcon(icon6)
        self.btn_birdview.setIconSize(QtCore.QSize(32, 32))
        self.btn_birdview.setAutoRaise(True)
        self.btn_birdview.setObjectName("btn_birdview")
        self.vbox_btn.addWidget(self.btn_birdview)
        self.vBox_left.addLayout(self.vbox_btn)
        self.vBox_left.setStretch(0, 2)
        self.vBox_left.setStretch(1, 1)
        self.vBox_left.setStretch(2, 8)
        self.splitter_right = QtWidgets.QSplitter(self.splitter_all)
        self.splitter_right.setOrientation(QtCore.Qt.Vertical)
        self.splitter_right.setObjectName("splitter_right")
        self.gBox_top = QtWidgets.QGroupBox(self.splitter_right)
        self.gBox_top.setAlignment(QtCore.Qt.AlignCenter)
        self.gBox_top.setObjectName("gBox_top")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gBox_top)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tView_ch_info = QtWidgets.QTableView(self.gBox_top)
        self.tView_ch_info.setObjectName("tView_ch_info")
        self.verticalLayout_3.addWidget(self.tView_ch_info)
        self.gBox_bottom = QtWidgets.QGroupBox(self.splitter_right)
        self.gBox_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.gBox_bottom.setObjectName("gBox_bottom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gBox_bottom)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tView_veh_static = QtWidgets.QTableView(self.gBox_bottom)
        self.tView_veh_static.setObjectName("tView_veh_static")
        self.verticalLayout_4.addWidget(self.tView_veh_static)
        self.horizontalLayout_6.addWidget(self.splitter_all)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pho/login.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_login, icon7, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Login)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.gBox_mode.setTitle(_translate("Login", "Mode"))
        self.lab_mode.setText(_translate("Login", "Mode:"))
        self.cBox_mode.setItemText(0, _translate("Login", "MF4"))
        self.cBox_mode.setItemText(1, _translate("Login", "XCP"))
        self.btn_mf4.setText(_translate("Login", "MF4"))
        self.cBox_resample.setText(_translate("Login", "Resample ?"))
        self.lab_mf4_file.setText(_translate("Login", "mf4-file-label"))
        self.gBox_search.setTitle(_translate("Login", "Search"))
        self.btn_load.setText(_translate("Login", "..."))
        self.btn_save.setText(_translate("Login", "..."))
        self.btn_check_all.setText(_translate("Login", "..."))
        self.btn_clear_all.setText(_translate("Login", "..."))
        self.btn_num.setText(_translate("Login", "..."))
        self.btn_yt.setText(_translate("Login", "..."))
        self.btn_birdview.setText(_translate("Login", "..."))
        self.gBox_top.setTitle(_translate("Login", "Selected Channel Info"))
        self.gBox_bottom.setTitle(_translate("Login", "Veh-Static"))
from . import resource_rc
