name: pydaymet-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - setuptools
  - pip
  - lxml

  - setuptools_scm
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage
  - pip:
    - git+https://github.com/cheginit/py3dep.git
