[tool.poetry]
name = "crf_tagger"
version = "0.1.0"
description = "CRF tagger"
authors = ["severinsimmler <s.simmler@snapaddy.com>"]

[tool.poetry.dependencies]
python = "^3.6"
tqdm = "^2.0"
python-crfsuite = "^0.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
