[tool.poetry]
name = "writeas-view-extractor"
version = "1.0.1"
description = "Extracts users posts from write.as"
authors = ["Mikko Uuksulainen <mikko.uuksulainen@uuksu.fi>"]

[tool.poetry.scripts]
writeas_view_extractor = "writeas_view_extractor.main:main"

[tool.poetry.dependencies]
python = "^3.6"
writeasapi = "^0.1.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
