# Generated by Django 2.1.7 on 2020-08-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0030_auto_20200809_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='password',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
