# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.RunSQL('update todo_todo set title=name where title is null')
    ]
