[tool.black]
    line-length = 100

[tool.poetry]
    name = "FAST-OAD"
    version = "v0.4.2-beta"
    description = "FAST-OAD is a framework for performing rapid Overall Aircraft Design"
    readme = "README.md"
    authors = [
        "Christophe DAVID <christophe.david@onera.fr>",
        "Scott DELBECQ <Scott.DELBECQ@isae-supaero.fr>"
    ]
    packages = [
        { include = "fastoad", from = "src" },
    ]
    homepage = "https://github.com/fast-aircraft-design/FAST-OAD"
    keywords = [
        "aircraft",
        "design",
        "multi-disciplinary"
    ]
    license = "GPL-3.0-only"
    classifiers = [
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Education",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Natural Language :: English",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Scientific/Engineering :: Physics"
    ]

[tool.poetry.dependencies]
    python = "^3.6.1"
    numpy = "*"
    scipy = "*"
    pandas = "^1"
    openmdao="^3 <3.2"
    lxml = "*"
    ipopo = "^1"
    jupyterlab = "*"
    matplotlib = "*"
    plotly = "*"
    ipywidgets = "*"
    importlib_resources = "*"
    ipysheet = "*"
    tomlkit = "^0.6.0"
    wop = "^1.9.0"

[tool.poetry.dev-dependencies]
    wheel = "*"
    pytest = "^5.2"
    pytest-cov = "*"
    pre-commit = "*"
    black = { version = "*", allow-prereleases = true }
    pylint = "*"
    nbval = "*"
    sphinx = "*"
    sphinx-rtd-theme = "*"
    sphinxcontrib-bibtex = "*"
    setuptools_scm = "*"

[tool.poetry.scripts]
    fastoad = "fastoad.cmd.fast:main"

[build-system]
    requires = ["poetry>=0.12"]
    build-backend = "poetry.masonry.api"
