[tool.coverage.paths]
source = ['handcalcs', '*/site-packages']

[tool.coverage.run]
branch = true
source = ['handcalcs']

[tool.coverage.report]
show_missing = true


[tool.poetry]
name = "handcalcs"
version = "0.8.1"
description = "Sample desc"
authors = ["Connor Ferster"]
license = "Apache-2.0"
homepage = "https://github.com/connorferster/handcalcs"
repository = "https://github.com/connorferster/handcalcs"
documentation = "https://github.com/connorferster/handcalcs"


[tool.poetry.dependencies]
python = "^3.7"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.9.0"
coverage = {extras = ["toml"], version = "^5.1"}
jupyterlab = "^2.1.5"
nbconvert = "^5.6.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
