language: python

addons:
  apt:
    packages:
    - latexmk
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - cd example

install:
  - pip install --upgrade pip
  - pip install ..
  - pip install sphinx_rtd_theme

script:
  - make clean html
  - make clean singlehtml
  - make clean dirhtml
  - make clean html WAVEDROM_HTML_NOJSINLINE=1
  - make clean singlehtml WAVEDROM_HTML_NOJSINLINE=1
  - make clean dirhtml WAVEDROM_HTML_NOJSINLINE=1
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then make clean latexpdf; fi
