[tool.poetry]
name = "spurious_emu"
version = "0.1.0"
description = "VBA static and dynamic analysis tool for malware analysts"
authors = ["Louis Dubois <ldbo@protonmail.com>"]
license = "AGPL-3.0-or-later"
readme= "Readme.md"
homepage = "https://github.com/ldbo/SpuriousEmu"
packages = [{include = "emu"}]
include = ["lib/*/*"]

[tool.poetry.scripts]
emu = "emu.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
oletools = "^0.55.1"
python-magic = "^0.4.18"
prettytable = "^0.7.2"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]
ipython = "^7.17.0"
nose = "^1.3.7"
coverage = "^5.2.1"
mypy = "^0.782"
networkx = "^2.4"
lxml = "^4.5.2"
matplotlib = "^3.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
