
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-22T03:15:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c39870fb866065c389cd5f0f440e7f40f63f40a",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
