[tool.poetry]
name = "django-q-rollbar"
version = "0.1.3"
description = "Bringing Rollbar error tracking to Django Q"
authors = ["Christo Goosen <christogoosen@gmail.com>", "Daniel Welch dwelch2102@gmail.com"]

[tool.poetry.dependencies]
python = "^3.6"
rollbar = "^0.14.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
