[build-system]
requires = ["setuptools >= 47.1.1", "wheel >= 0.34.2"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
src_paths = ["iseq"]
known_third_party = ["appdirs", "brotli", "click", "fasta_reader",
                     "hmmer_reader", "imm", "nmm", "numpy", "pandas",
                     "pytest", "ray", "requests", "setuptools", "tqdm",
                     "in_place", "humanfriendly", "seaborn", "matplotlib",
                     "Bio", "biopython", "importlib_resource", "hmmer"]

[tool.pylint.message_control]
disable = """
  C0330,
  R0915,
  apply-builtin,
  backtick,
  bad-inline-option,
  bad-python3-import,
  basestring-builtin,
  buffer-builtin,
  cmp-builtin,
  cmp-method,
  coerce-builtin,
  coerce-method,
  comprehension-escape,
  delslice-method,
  deprecated-itertools-function,
  deprecated-operator-function,
  deprecated-pragma,
  deprecated-str-translate-call,
  deprecated-string-function,
  deprecated-sys-function,
  deprecated-types-field,
  deprecated-urllib-function,
  dict-items-not-iterating,
  dict-iter-method,
  dict-keys-not-iterating,
  dict-values-not-iterating,
  dict-view-method,
  div-method,
  eq-without-hash,
  exception-escape,
  exception-message-attribute,
  execfile-builtin,
  file-builtin,
  file-ignored,
  filter-builtin-not-iterating,
  getslice-method,
  hex-method,
  idiv-method,
  import-outside-toplevel,
  import-star-module-level,
  indexing-exception,
  input-builtin,
  intern-builtin,
  invalid-name,
  invalid-str-codec,
  line-too-long,
  line-too-long,
  locally-disabled,
  long-builtin,
  long-suffix,
  map-builtin-not-iterating,
  metaclass-assignment,
  missing-class-docstring,
  missing-function-docstring,
  missing-module-docstring,
  missing-module-docstring,
  next-method-called,
  next-method-defined,
  no-absolute-import,
  non-ascii-bytes-literal,
  nonzero-method,
  oct-method,
  old-division,
  old-ne-operator,
  old-octal-literal,
  old-raise-syntax,
  parameter-unpacking,
  print-statement,
  raising-string,
  range-builtin-not-iterating,
  raw-checker-failed,
  raw_input-builtin,
  rdiv-method,
  redefined-builtin,
  redefined-builtin,
  redefined-outer-name,
  reduce-builtin,
  reload-builtin,
  round-builtin,
  setslice-method,
  standarderror-builtin,
  suppressed-message,
  sys-max-int,
  too-few-public-methods,
  too-many-arguments,
  too-many-function-args,
  too-many-instance-attributes,
  too-many-locals,
  too-many-public-methods,
  too-many-statements,
  unichr-builtin,
  unicode-builtin,
  unpacking-in-except,
  use-symbolic-message-instead,
  useless-suppression,
  using-cmp-argument,
  xrange-builtin,
  xreadlines-attribute,
  zip-builtin-not-iterating,
  protected-access,
"""
