#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ns_stitchclient', 'ns_stitchclient.transit']

package_data = \
{'': ['*']}

install_requires = \
['python-dateutil>=2.7.3', 'msgpack-python', 'requests==2.20.0']

setup(name='ns_stitchclient',
      version='0.7.0.post1',
      description='A Stitch Import API client library for python',
      author='Stitch',
      author_email='support@stitchdata.com',
      url='https://github.com/stitchdata/python-stitch-client',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6,<4',
     )
