# Generated by Django 2.1.5 on 2020-06-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200614_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name_of_month',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
