# Generated by Django 3.0.6 on 2020-06-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200303_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='pages.Pages'),
        ),
    ]
