[tool.poetry]
name = "tinycardl"
version = "1.0.0"
description = "Download your cards"
authors = ["Baptiste Darthenay <baptiste.darthenay@gmail.com>"]
license = "MIT"
repository = "https://github.com/batisteo/tinycardl"
readme = "README.md"
packages = [ { include = "tinycardl" } ]

[tool.poetry.scripts]
tinycardl = "tinycardl:main.entrypoint"

[tool.poetry.dependencies]
python = "^3.8"
aiocsv = "^1.1.0"
aiofiles = "^0.5.0"
aioify = "^0.3.2"
httpx = "^0.14.1"
httpx-auth = "^0.5.0"
python-jose = "^3.2.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
bpython = "^0.19"
flake8 = "^3.8.3"
mypy = "^0.782"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
