"""
File containing all of the Mojave event types in the mlflow. namespace.
"""

# Usage related events
CLIENT_CREATE_EXPERIMENT = "CLIENT.CREATE_EXPERIMENT"
CLIENT_END_RUN = "CLIENT.END_RUN"
CLIENT_LOG_ARTIFACT = "CLIENT.LOG_ARTIFACT"
CLIENT_LOG_MODEL = "CLIENT.LOG_MODEL"
CLIENT_START_RUN = "CLIENT.START_RUN"
SERVER_CREATE_EXPERIMENT = "SERVER.CREATE_EXPERIMENT"
SERVER_CREATE_RUN = "SERVER.CREATE_RUN"
SERVER_LOG_MODEL = "SERVER.LOG_MODEL"

# Performance related events
CLIENT_CREATE_SNAPSHOT = "CLIENT.CREATE_SNAPSHOT"
CLIENT_GET_KERNEL_INFO = "CLIENT.GET_KERNEL_INFO"
CLIENT_PUT_KERNEL_MESSAGE = "CLIENT.PUT_KERNEL_MESSAGE"
SERVER_LIST_EXPERIMENTS_DETAILED = "SERVER.LIST_EXPERIMENTS_DETAILED"

# Error logging events
CLIENT_GET_KERNEL_INFO_ERROR = "CLIENT.GET_KERNEL_INFO_ERROR"
CLIENT_PUT_KERNEL_MESSAGE_ERROR = "CLIENT.PUT_KERNEL_MESSAGE_ERROR"
CLIENT_SNAPSHOT_CREATION_ERROR = "CLIENT.SNAPSHOT_CREATION_ERROR"
MLFLOW_EXCEPTION = "MLFLOW.EXCEPTION"
