#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['image', 'image.migrations', 'image.templatetags', 'image.tests']

package_data = \
{'': ['*'],
 'image': ['management/*',
           'management/commands/*',
           'static/*',
           'static/image/*',
           'templates/*',
           'templates/image/*'],
 'image.tests': ['news_article/*']}

install_requires = \
['unidecode']

setup(name='django-img',
      version='0.0.1',
      description='Image handling for Django. Includes upload code, repository and filter creation. Low on features, fast setup, modular.',
      author='robert crowther',
      author_email='rw.crowther@gmail.com',
      url='https://github.com/rcrowther/django-image',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
