# Generated by Django 2.2 on 2020-07-09 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DEACTIVE', 'deactive')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
