# Generated by Django 2.2.5 on 2020-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191016_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='menu/', verbose_name='Иконка'),
        ),
    ]
