[tool.poetry]
name = "essnapshot"
version = "0.1.0"
description = "Tool for Elasticsearch snapshot creation and rotation."
authors = ["gricertg <gricertg@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/gricertg/essnapshot"
repository = "https://github.com/gricertg/essnapshot"


[tool.poetry.dependencies]
python = "^3.6"
elasticsearch = "^7.8.1"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"
pytest-docker = "^0.8.0"
pytest-integration = "^0.2.2"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
essnapshot = 'essnapshot.cli:main'