[tool.poetry]
name = "destiny"
version = "0.1.0"
description = ""
authors = ["Tomas Pereira de Vasconcelos <tomasvasconcelos1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.0"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
