# Generated by Django 2.1.7 on 2020-08-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20200824_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Perfil'),
        ),
    ]
