# Generated by Django 2.1.7 on 2020-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_perfil_perfil_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilgrupo',
            name='dat_fim',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='perfilgrupo',
            name='dat_ini',
            field=models.DateField(null=True),
        ),
    ]
