[tool.poetry]
name = "django-rapidapi"
version = "0.1.0-dev1"
description = "Django API extension"
authors = ["Anton Ruhlov <antonruhlov@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/antonrh/django-apirouter"
keywords = ["django", "api", "rest"]
packages = [
    { include = "rapidapi", from = "." },
]

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.1"
mkdocs = {version = "^1.1.2", extras = ["docs"]}
mkdocs-material = {version = "^5.5.9", extras = ["docs"]}

[tool.poetry.dev-dependencies]
isort = "^5.4.2"
black = "^20.8b1"
mypy = "^0.782"
flake8 = "^3.8.3"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-django = "^3.9.0"
bump2version = "^1.0.0"
safety = "^1.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
