[tool.poetry]
name = "pyspare"
version = "0.0.1"
description = "pretty print"
authors = ["Hoyeung Wong <hoyeungw@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pydget/pyspare"
repository = "https://github.com/pydget/pyspare"
keywords = [
    "console", "log", "pretty", "colorful", "terminal", "command-line",
    "list", "array", "vector", "matrix", "1d-list", "2d-list",
    "map", "mapper", "mutate", "zipper", "enumerate", "iterate",
    "entry", "entries", "key-value", "key-value pairs",
    "dict", "object", "json"
]

[tool.poetry.dependencies]
python = "^3.8"
aryth = ">=0.0.6"
intype = ">=0.0.2"
ject = ">=0.0.1"
palett = ">=0.0.4"
veho = ">=0.0.4"
texting = ">=0.0.8"

[tool.poetry.dev-dependencies]
pytest = ">=6.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
