name: flowsym-environment
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - hdbscan
  - setuptools
  - click
  - pytest
  - seaborn
  - pip
  - pip:
    - fcsy
    - unidip