  # Base Configuration for Artella Assets

# Defines the file that is used to retrieve asset info if no production tracker is used
data_filename: "data.json"

# Defines dictionary of asset types (Props, Characters, etc) used by the project
types: {}

# Defines list of files that must be available to consider an asset published
must_file_types: []

# Defines list of paths that should be ignored during asset searching
ignored_paths: []

# Defines the Work In Progress status assets
wip_status: "working"

# Defines the Published status for assets
publish_status: "published"

# Defines the default size used by asset thumbs
thumb_size: [200, 200]

# Defines the name of the icon used by default in asset thumbs
default_thumb: 'default'

# Defines the default name used by assets
default_name: 'New Asset'

# Shading file type used by assets
shading_file_type: 'shading'

# Shaders Mapping file type used by assets
shaders_mapping_file_type: 'shadersmapping'

# Defines dictionary with default asset data info
data:
  id_attribute: 'id'
  name_attribute: 'name'
  thumb_attribute: 'thumb'
  description_attribute: 'description'
  icon_attribute: 'icon'
  category_attribute: 'category'
  path_template_name: 'asset_path'