[tool.poetry]
name = "zeroconf-service"
version = "1.1.0"
description = ""
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
zeroconf = "^0.28.1"
compress-pickle = "^1.2.0"
websockets = "^8.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
pdoc3 = "^0.8.4"
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
