[tool.poetry]
name = "linefolio"
version = "1.2.0"
description = "Backtest performance analysis and charting for MoonLine, but with pyfolio."
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
ipython = "^7.17.0"
matplotlib = "^3.3.1"
numpy = "^1.19.1"
pandas = "^1.1.1"
pytz = "^2020.1"
scipy = "^1.5.2"
scikit-learn = "^0.23.2"
seaborn = "^0.10.1"
empyrical = "^0.5.3"
quantrocket-moonshot = "^2.1.0"
quantrocket-moonchart = "^2.0.1"

[tool.poetry.dev-dependencies]
pdoc3 = "^0.8.4"
flake8 = "^3.8.3"
pytest = "^6.0.1"
nose-parameterized = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
