
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-25T00:22:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "33fcf51b55da19ccad41b68de80cea9d6a3e5fc4",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
