[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "cppcpyutils"
author = "Dominik Schneider"
author-email = "dominik.schneider@wsu.edu"
home-page = "https://github.com/CougPhenomics/cppcpyutils"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

