
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-21T12:40:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ba3d0a7417bed3d0c2be556df5a37b12369fc55",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
