[tool.poetry]
name = "quaternionic"
version = "0.1.9"
description = "Interpret numpy arrays as quaternionic arrays with numba acceleration"
readme = "README.md"
license = "MIT"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]
homepage = "https://github.com/moble/quaternionic"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = "^1.0", python = "<3.8"}
numpy = "^1.13"
scipy = "^1.0"
numba = {version = "^0.50", markers = "implementation_name == 'cpython'"}
mkdocs = {version = "^1.1.2", optional = true, markers = "implementation_name == 'cpython'"}
mktheapidocs = {extras = ["plugin"], version = "^0.2.0", optional = true, markers = "implementation_name == 'cpython'"}
python-markdown-math = {version = "^0.7", optional = true, markers = "implementation_name == 'cpython'"}

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.10.1"
mkdocs = {version = "^1.1.2", markers = "implementation_name == 'cpython'"}
mktheapidocs = {extras = ["plugin"], version = "^0.2.0", markers = "implementation_name == 'cpython'"}
python-markdown-math = {version = "^0.7", markers = "implementation_name == 'cpython'"}
black = {version = "^19.10b0", markers = "implementation_name == 'cpython'"}

[tool.poetry.extras]
mkdocs = ["mkdocs"]
mktheapidocs = ["mktheapidocs"]
python-markdown-math = ["python-markdown-math"]

[tool.black]
line-length = 120
target-version = ['py36']

[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ".* build dist *.egg-info install ENV"
junit_family="xunit2"
addopts = "-v --tb=short --doctest-glob='' --cov --cov-branch --cov-report xml"

[build-system]
requires = ["poetry-core>=1.0.0a9"]
build-backend = "poetry.core.masonry.api"
