[tool.poetry]
name = "blandfeed"
version = "0.1.3"
description = "Push feed for your device, easy to setup, mediocre to use"
authors = ["rendaw"]
include = ["blandfeed/libsodium.js"]

[tool.poetry.dependencies]
python = "^3.7"
dbus-python = "^1.2.16"
pygobject = "^3.36.1"
aiohttp = "^3.6.2"
appdirs = "^1.4.4"
pynacl = "^1.4.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
blandfeed = "blandfeed.main:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

