[tool.poetry]
name = "pelican"
version = "4.5.0"
description = "Static site generator supporting Markdown and reStructuredText"
authors = ["Justin Mayer <entrop@gmail.com>"]
license = "AGPLv3"
readme = "README.rst"
keywords = ["static site generator", "static sites", "ssg"]

homepage = "https://getpelican.com"
repository = "https://github.com/getpelican/pelican"
documentation = "https://docs.getpelican.com"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"Funding" = "https://donate.getpelican.com/"
"Tracker" = "https://github.com/getpelican/pelican/issues"

[tool.poetry.dependencies]
python = "^3.6"
blinker = "^1.4"
docutils = "^0.16"
feedgenerator = "^1.9"
jinja2 = "~2.11"
pygments = "~2.6.1"
python-dateutil = "^2.8"
pytz = "^2020.1"
unidecode = "^1.1"
markdown = {version = "~3.2.2", optional = true}

[tool.poetry.dev-dependencies]
BeautifulSoup4 = "^4.9"
lxml = "^4.3"
markdown = "~3.2.2"
typogrify = "^2.0"
sphinx = "^3.0"
sphinx_rtd_theme = "^0.5"
livereload = "^2.6"
pytest = "^6.0"
pytest-cov = "^2.8"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.4"
pytest-xdist = "^2.0"
tox = "^3.13"
flake8 = "^3.8"
flake8-import-order = "^0.18.1"
invoke = "^1.3"
isort = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.extras]
markdown = ["markdown"]

[tool.poetry.scripts]
pelican = "pelican.__main__:main"
pelican-import = "pelican.tools.pelican_import:main"
pelican-plugins = "pelican.plugins._utils:list_plugins"
pelican-quickstart = "pelican.tools.pelican_quickstart:main"
pelican-themes = "pelican.tools.pelican_themes:main"

[tool.autopub]
project-name = "Pelican"
git-username = "botpub"
git-email = "botpub@autopub.rocks"
changelog-file = "docs/changelog.rst"
changelog-header = "###############"
version-header = "="
version-strings = ["setup.py"]
build-system = "setuptools"

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
