#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yahoo_finance_async']

package_data = \
{'': ['*']}

install_requires = \
['aiohttp>=3.6.2', 'aiodns>=2.0.0']

setup(name='yahoo_finance_async',
      version='0.1.0',
      description='A Python async API wrapper for the deprecated (but currently still working) Yahoo Finance API',
      author='Matt Gosden',
      author_email='mdgosden@gmail.com',
      url='https://github.com/ttamg/yahoo_finance_async',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
