#   Copyright (c) 2020 Lenovo.  All rights reserved.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


"""
    CP Web Services (CPWS)

    CP web services provides API access to the ThinkAgile CP on-premises cloud platform. It provides access to virtual datacenter and infrastructure resources and is used to create resizable resources, manage workloads and retrieve information about the underlying infrastructure. CPWS will continue to grow as new capabilities are added to the platform.  # noqa: E501

    OpenAPI spec version: Beta
    Contact: lenovo-email
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tacp
from api.storage_controllers_api import StorageControllersApi  # noqa: E501
from tacp.rest import ApiException


class TestStorageControllersApi(unittest.TestCase):
    """StorageControllersApi unit test stubs"""

    def setUp(self):
        self.api = api.storage_controllers_api.StorageControllersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_storage_controller_information_using_get(self):
        """Test case for get_storage_controller_information_using_get

        View the properties of a storage controller  # noqa: E501
        """
        pass

    def test_get_storage_controllers_using_get(self):
        """Test case for get_storage_controllers_using_get

        View storage controllers for an organization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
