
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T17:57:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff693c467285fe55a9069fd4bc42ce90a0d1935e",
 "version": "v0.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
