# Base Configuration file for artellapipe-tools-namemanager in Plot Twist

# Defines icon of the tool
icon: namemanager

# URL to tool documentation web page
help_url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/namemanager/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False
