# Base Configuration file for artellapipe-tools-artellauploader in Solstice

# Defines icon of the tool
icon: dependenciesmanager

# URL to tool documentation web page
help_url: https://solstice-short-film.github.io/solstice-docs/pipeline/pipeline/tools/dependenciesmanager/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False