XX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XX
   XXXXXXXXXXXXXXXXX XX XXX XXX XX XXXXXXXX XXXXX
   XXX XXX XXXXX XXXX XXXX XXXXXXXXXX XX XXXX XXXXXXX XXX XX XXXXXX XX XXXXX
   XXXXXXX XXX XXXX XXXXXXXXX XXXXXXXXXX

XXXXX XXXXXXXXXX X XXXXXXXXXXXX XXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXX
   XXXXXXXXXX X
   XXXXXXXXXX


   XXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXX
   XXXXXXXXXXX
   XXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXX
   XXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXX


XXXXXXX XXX XXXXXX
XXXXXXXXXXXXXXXXXX

X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXX
