# Generated by Django 2.1.7 on 2020-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0010_auto_20200806_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupouser',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grupouser',
            name='dat_fim',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grupouser',
            name='dat_ini',
            field=models.DateField(null=True),
        ),
    ]
