# Generated by Django 2.1.7 on 2020-08-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0011_auto_20200825_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupouser',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='origem_delete',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='origem_edicao',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='origem_insercao',
        ),
        migrations.RemoveField(
            model_name='grupouser',
            name='usr',
        ),
        migrations.DeleteModel(
            name='GrupoUser',
        ),
    ]
