# Base Configuration file for artellapipe-tools-artellauploader in Plot Twist

# Defines icon of the tool
icon: artellauploader

# URL to tool documentation web page
help_url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/artellauploader/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False