
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-28T12:35:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "421746e36a9b3fafb1114d6e18eab47e692ba1b7",
 "version": "0.82.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
