name: pygeoogc-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - setuptools
  - owslib
  - pyproj
  - orjson
  - shapely
  - defusedxml
  - requests

  - bump2version
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage

