title = "Sample OAD Process"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = []

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='COBYLA')"

# Definition of OpenMDAO model
[model]
    # Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=200)"
    linear_solver = "om.DirectSolver()"

    # Although "model" is a mandatory name for the top level of the model, its
    # sub-components can be freely named by user
    [model.geometry]
        # An OpenMDAO component is identified by its "id"
        id = "fastoad.geometry.legacy"
    [model.weight]
        id = "fastoad.weight.legacy"
    [model.mtow]
        id = "fastoad.loop.mtow"
    [model.aerodynamics.highspeed]
        id = "fastoad.aerodynamics.highspeed.legacy"
    [model.aerodynamics.landing]
        id = "fastoad.aerodynamics.landing.legacy"
        use_xfoil = false
    [model.performance]
        id = "fastoad.performances.breguet"
    [model.propulsion]
        id = "fastoad.propulsion.rubber_engine"
    [model.hq.tail_sizing]
        id = "fastoad.handling_qualities.tail_sizing"
    [model.hq.static_margin]
        id = "fastoad.handling_qualities.static_margin"
    [model.wing_area]
        id = "fastoad.loop.wing_area"

[optimization]  # This section is needed only if optimization process is run
    [[optimization.design_var]]
            name = "data:geometry:wing:MAC:at25percent:x"
            lower = 16.0
            upper = 18.0

    [[optimization.constraint]]
            name = "data:handling_qualities:static_margin"
            lower = 0.05
            upper = 0.1

[[optimization.objective]]
            name = "data:mission:sizing:fuel"
