# Generated by Django 2.1.7 on 2020-07-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20200716_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteerro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clientelog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clientequery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fornecedorerro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fornecedorlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fornecedorquery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='indicadorerro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='indicadorlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='indicadorquery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='processoserro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='processoslog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='processosquery',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venda_maiserro',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venda_maislog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venda_maisquery',
            options={'managed': True},
        ),
    ]
