# Generated by Django 2.1.7 on 2020-07-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filialhorafuncionamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filialservico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'managed': False},
        ),
    ]
