
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-26T17:09:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ffaabd015d360055a0b031d711c5be9c4b2e175",
 "version": "1.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
