
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-18T14:12:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c27c2d2e00b7e267448d027809b8754bdea50db",
 "version": "0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
