
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-21T22:17:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9006fa614643deb1b1556c9f9dc049cbd9951e05",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
