FILE = ''
DIR = ''
SUBDIR = '﬌'

SYMLINK_FILE = ''
SYMLINK_DIR = ''
SYMLINK_PTR = 'ﰲ'

ARCHIVE = ''
AUDIO = 'ﱘ'
CONFIG = ''
IMAGE = ''
SHELL = ''
SUBL = ''
VIDEO = ''
WIN_EXECUTABLE = ''

C_LANG = ''
CPP = ''
CS = ''
CLOJURE = ''
PYTHON = ''

EXTENSIONS = {
    '.apk': '',
    '.c': C_LANG,
    '.h': C_LANG,
    '.hpp': CPP,
    '.hxx': CPP,
    '.cfg': CONFIG,
    '.clj': CLOJURE,
    '.cljc': CLOJURE,
    '.cljs': CLOJURE,
    '.coffee': '',
    '.cc': CPP,
    '.cp': CPP,
    '.cpp': CPP,
    '.cxx': CPP,
    '.cs': CS,
    '.csproj': CS,
    '.csx': CS,
    '.css': '',
    '.d': '',
    '.dart': '',
    '.db': '',
    '.ds_store': '',
    '.ipynb': PYTHON,
    '.md': '',
    '.py': PYTHON,
    '.pyc': PYTHON,
    '.psd': '',
    '.rs': '',
    '.vue': '﵂',
    '.sln': "",
    '.sql': "",
    '.sqlite3': "",
    '.sublime_keymap': SUBL,
    '.sublime_package': SUBL,
    '.sublime_settings': SUBL,
    '.sublime_theme': SUBL,
    '.txt': '',
    'ps1': SHELL,
    'sh': SHELL,
    'shell': SHELL,

    # Everything below needs to be in sync with EXTENSION_TO_CATEGORY
    '.7z': ARCHIVE,
    '.a': ARCHIVE,
    '.ar': ARCHIVE,
    '.bz2': ARCHIVE,
    '.cab': ARCHIVE,
    '.cpio': ARCHIVE,
    '.deb': ARCHIVE,
    '.dmg': ARCHIVE,
    '.egg': ARCHIVE,
    '.gz': ARCHIVE,
    '.iso': ARCHIVE,
    '.jar': ARCHIVE,
    '.lha': ARCHIVE,
    '.mar': ARCHIVE,
    '.pak': ARCHIVE,
    '.pea': ARCHIVE,
    '.rar': ARCHIVE,
    '.rpm': ARCHIVE,
    '.s7z': ARCHIVE,
    '.shar': ARCHIVE,
    '.tar': ARCHIVE,
    '.tbz2': ARCHIVE,
    '.tgz': ARCHIVE,
    '.tlz': ARCHIVE,
    '.war': ARCHIVE,
    '.whl': ARCHIVE,
    '.xpi': ARCHIVE,
    '.xz': ARCHIVE,
    '.zip': ARCHIVE,
    '.zipx': ARCHIVE,

    '.bat': WIN_EXECUTABLE,
    '.exe': WIN_EXECUTABLE,
    '.msi': WIN_EXECUTABLE,

    '.3dm': IMAGE,
    '.3ds': IMAGE,
    '.ai': IMAGE,
    '.bmp': IMAGE,
    '.dds': IMAGE,
    '.dwg': IMAGE,
    '.dxf': IMAGE,
    '.eps': IMAGE,
    '.gif': IMAGE,
    '.gpx': IMAGE,
    '.jpeg': IMAGE,
    '.jpg': IMAGE,
    '.kml': IMAGE,
    '.kmz': IMAGE,
    '.max': IMAGE,
    '.png': IMAGE,
    '.ps': IMAGE,
    '.svg': IMAGE,
    '.tga': IMAGE,
    '.thm': IMAGE,
    '.tif': IMAGE,
    '.tiff': IMAGE,
    '.webp': IMAGE,
    '.xcf': IMAGE,

    '.aac': AUDIO,
    '.aiff': AUDIO,
    '.ape': AUDIO,
    '.au': AUDIO,
    '.flac': AUDIO,
    '.gsm': AUDIO,
    '.it': AUDIO,
    '.m3u': AUDIO,
    '.m4a': AUDIO,
    '.mid': AUDIO,
    '.mod': AUDIO,
    '.mp3': AUDIO,
    '.mpa': AUDIO,
    '.pls': AUDIO,
    '.ra': AUDIO,
    '.s3m': AUDIO,
    '.sid': AUDIO,
    '.wav': AUDIO,
    '.wma': AUDIO,
    '.xm': AUDIO,

    '.3g2': VIDEO,
    '.3gp': VIDEO,
    '.aaf': VIDEO,
    '.asf': VIDEO,
    '.avchd': VIDEO,
    '.avi': VIDEO,
    '.drc': VIDEO,
    '.flv': VIDEO,
    '.m2v': VIDEO,
    '.m4p': VIDEO,
    '.m4v': VIDEO,
    '.mkv': VIDEO,
    '.mng': VIDEO,
    '.mov': VIDEO,
    '.mp2': VIDEO,
    '.mp4': VIDEO,
    '.mpe': VIDEO,
    '.mpeg': VIDEO,
    '.mpg': VIDEO,
    '.mpv': VIDEO,
    '.mxf': VIDEO,
    '.nsv': VIDEO,
    '.ogg': VIDEO,
    '.ogm': VIDEO,
    '.ogv': VIDEO,
    '.qt': VIDEO,
    '.rm': VIDEO,
    '.rmvb': VIDEO,
    '.roq': VIDEO,
    '.srt': VIDEO,
    '.svi': VIDEO,
    '.vob': VIDEO,
    '.webm': VIDEO,
    '.wmv': VIDEO,
    '.yuv': VIDEO,
}
