[tool.poetry]
name = "parchmint"
version = "0.1.1"
description = "ParchMint object library for Python"
authors = ["Radhakrishna Sanka <rkrishnasanka@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.4"
networkx = "^2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
