name: automated_build

on:
  release:
    types: [published]

jobs:
  dist:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python_version: 3.x
    
    - name: Install requirement
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=42.0" "setuptools_scm[toml]>=4.1" "wheel" "twine"
        
    - name: Build SDist
      run: |
        python setup.py sdist
    
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
    
    - name: Build wheel
      run: python -m pip wheel . -w wheels
    
    - uses: actions/upload-artifact@v2
      with:
        path: wheels/pyBumpHunter-*.whl
    
    - name: Check metadata
      run: |
        twine check dist/* wheels/*
  
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        user: __token__
        password: ${{secrets.PYTOKEN}}


