- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-tempest-functional-python3
        - ironic-grenade
        # Temporary disable voting because of end of cycle CI instability.
        - ironic-grenade-dsvm-multinode-multitenant:
            voting: false
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-indirect
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-pxe_snmp:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-managed:
            voting: false
        - ironic-inspector-tempest-partition-bios-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - ironic-tempest-pxe_ipmitool-postgres:
            voting: false
        - ironic-tempest-ipxe-ipv6:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-tempest-functional-python3
        - ironic-grenade
        # removing from voting due to end of cycle gate instability.
        # - ironic-grenade-dsvm-multinode-multitenant
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-indirect
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
    experimental:
      jobs:
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
