[tool.poetry]
name = "TypedSch"
version = "0.0.0"
description = ""
authors = ["iyanging <iyanging@163.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pre-commit = "^2.6.0"
commitizen = "^2.1.0"

[tool.isort]
known_third_party = []

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 79
