
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-23T22:45:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f1371fe5cfdf40672f4f3ba7ea91b81e52a6be2",
 "version": "4.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
