# Generated by Django 2.1.7 on 2020-07-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_auto_20200715_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupouser',
            options={'managed': False},
        ),
    ]
