# Generated by Django 2.1.7 on 2020-08-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0020_auto_20200824_1521'),
        ('filial', '0022_auto_20200820_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.Funcionario'),
        ),
    ]
