[tool.poetry]
name = "dapodik"
version = "0.1.0"
description = "Client & alat bantu aplikasi Dapodik"
authors = ["hexatester <habibrohman@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hexatester/dapodik"
repository = "https://github.com/hexatester/dapodik"
include = [
    "LICENSE",
    "LISENSI",
    "README.md",
    "README-EN.md",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"
openpyxl = "^3.0.4"
click = "^7.1.2"
dacite = "^1.5.1"
cachetools = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"
autopep8 = "^1.5.3"

[tool.poetry.scripts]
dapodik = "dapodik.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
