apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: illuminatio
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - patch
  - get
  - list
  - watch
