[tool.poetry]
name = "openqlab"
version = "0.2.2"
description = "An open-source collection of tools for quantum-optics experiments"
authors = [
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
]
maintainers = [
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
]
readme = "README.md"
repository = "https://gitlab.com/las-nq/openqlab"
documentation = "https://las-nq-serv.physnet.uni-hamburg.de/python/openqlab/"

[tool.poetry.dependencies]
python = "^3.6.1"
pyserial = "^3.4"
numpy = "^1.18.2"
matplotlib = "^3.2.1"
tabulate = "^0.8.7"
pytimeparse = "^1.1.8"
pytz = "^2019.3"
pathlib = "^1.0.1"
statsmodels = "^0.11.1"
psutil = "^5.7.0"
jsonpickle = "^1.4"
multiprocess = "^0.70.9"
dill = "^0.3.1"
requests = "^2.23.0"
DateTime = "^4.3"
pyvisa = "^1.10.1"
pyvisa-py = "^0.3.1"
tables = "^3.6.1"
cufflinks = "^0.17.3"
scipy = "^1.4.1"
pandas = "~1.1"
six = "^1.14.0"
python-dateutil = "^2.8.1"
eml-parser = "^1.11.6"
importlib-metadata = {version = "^1.1.3", python = "<=3.7"}


[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
recommonmark = "^0.6.0"
docutils = "^0.16"
sphinx-markdown-tables = "^0.0.12"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
sphinx-rtd-theme = "^0.4.3"
twine = "^3.1.1"
mypy = "^0.770"
pylint = "^2.4.4"
sphinx = "^2.4"
pre-commit = "^2.2.0"
pydocstyle = "^5.0.2"
isort = "^4.3.21"
seed-isort-config = "^2.1.1"
ipython = "^7.13.0"
rope = "^0.16.0"
py2exe = "^0.9.2"  # Needed for tk on Windows
pydocstring = "^0.2.1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
