- hosts: all
  name: Autoconverted job legacy-neutron-dynamic-routing-dsvm-tempest-api from old
    job gate-neutron-dynamic-routing-dsvm-tempest-api
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          INSTALL_TEMPEST=True
          enable_plugin neutron-dynamic-routing https://opendev.org/openstack/neutron-dynamic-routing
          enable_plugin neutron-tempest-plugin https://opendev.org/openstack/neutron-tempest-plugin

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export DEVSTACK_GATE_USE_PYTHON3=True
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          if [ "ZUUL_BRANCH" == "stable/newton" ]; then
              export DEVSTACK_GATE_TEMPEST_REGEX="^neutron_dynamic_routing\."
          else
              export DEVSTACK_GATE_TEMPEST_REGEX="^neutron_dynamic_routing.tests.tempest.api\."
          fi
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1
          export DEVSTACK_GATE_NEUTRON=1
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          export PROJECTS="openstack/neutron-dynamic-routing $PROJECTS"
          export PROJECTS="openstack/neutron-tempest-plugin $PROJECTS"

          if [ "ZUUL_BRANCH" != "stable/newton" ]; then
              function gate_hook {
                  bash -xe $BASE/new/neutron-dynamic-routing/neutron_dynamic_routing/tests/contrib/gate_hook.sh dsvm-api
              }
              export -f gate_hook
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
