# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FuelLevelProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EventHeaderProto_pb2 as EventHeaderProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FuelLevelProto.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x46uelLevelProto.proto\x1a\x16\x45ventHeaderProto.proto\"\xe5\x02\n\tFuelLevel\x12\x1c\n\x06header\x18\x01 \x02(\x0b\x32\x0c.EventHeader\x12\x1c\n\x14\x66uel_level_low_limit\x18\x0b \x01(\r\x12\x12\n\nmil_status\x18\x02 \x01(\r\x12\x0b\n\x03rpm\x18\x03 \x01(\r\x12\x19\n\x11throttle_position\x18\x04 \x01(\r\x12\x19\n\x11\x65ngine_load_value\x18\x05 \x01(\r\x12\x19\n\x11\x65ngine_load_limit\x18\x06 \x01(\r\x12\x1e\n\x16\x65ngine_load_time_limit\x18\x07 \x01(\r\x12\"\n\x1a\x65ngine_coolant_temperature\x18\x08 \x01(\x11\x12(\n engine_coolant_temperature_limit\x18\t \x01(\r\x12\x18\n\x10\x66uel_level_value\x18\n \x01(\r\x12\"\n\x1ainstantaneous_fuel_economy\x18\x0c \x01(\r')
  ,
  dependencies=[EventHeaderProto__pb2.DESCRIPTOR,])




_FUELLEVEL = _descriptor.Descriptor(
  name='FuelLevel',
  full_name='FuelLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='FuelLevel.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuel_level_low_limit', full_name='FuelLevel.fuel_level_low_limit', index=1,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mil_status', full_name='FuelLevel.mil_status', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpm', full_name='FuelLevel.rpm', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle_position', full_name='FuelLevel.throttle_position', index=4,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_load_value', full_name='FuelLevel.engine_load_value', index=5,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_load_limit', full_name='FuelLevel.engine_load_limit', index=6,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_load_time_limit', full_name='FuelLevel.engine_load_time_limit', index=7,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_coolant_temperature', full_name='FuelLevel.engine_coolant_temperature', index=8,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_coolant_temperature_limit', full_name='FuelLevel.engine_coolant_temperature_limit', index=9,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuel_level_value', full_name='FuelLevel.fuel_level_value', index=10,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instantaneous_fuel_economy', full_name='FuelLevel.instantaneous_fuel_economy', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=406,
)

_FUELLEVEL.fields_by_name['header'].message_type = EventHeaderProto__pb2._EVENTHEADER
DESCRIPTOR.message_types_by_name['FuelLevel'] = _FUELLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuelLevel = _reflection.GeneratedProtocolMessageType('FuelLevel', (_message.Message,), dict(
  DESCRIPTOR = _FUELLEVEL,
  __module__ = 'FuelLevelProto_pb2'
  # @@protoc_insertion_point(class_scope:FuelLevel)
  ))
_sym_db.RegisterMessage(FuelLevel)


# @@protoc_insertion_point(module_scope)
