# Configuration file for the Binary_Network
---
train_new: True # If True, trains a new neural network and overwrites the current trained_model.pth file

Binary_Network:
  num_epochs: 60 # Number of passes over the training data
  optimiser:
    learning_rate: 0.01 # Parameter multiplied to the weight updates during stochastic gradient descent - Uses Adam optimiser
  initialisations:
    weight_init: xavier # type of initialisation used for the model weights, Xavier is currently recommended
    hidden_dim: 7 # Number of neurons in the hidden layers
