# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://www.sumup.ai/apis/#nucleus-documentation  # noqa: E501

    OpenAPI spec version: v4.0.9
    Contact: info@sumup.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AuthorConnectL2RespModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keywords': 'str',
        'authors': 'list[str]'
    }

    attribute_map = {
        'keywords': 'keywords',
        'authors': 'authors'
    }

    def __init__(self, keywords=None, authors=None):  # noqa: E501
        """AuthorConnectL2RespModel - a model defined in Swagger"""  # noqa: E501

        self._keywords = None
        self._authors = None
        self.discriminator = None

        if keywords is not None:
            self.keywords = keywords
        if authors is not None:
            self.authors = authors

    @property
    def keywords(self):
        """Gets the keywords of this AuthorConnectL2RespModel.  # noqa: E501

        Topic discussed by target author and connected authors  # noqa: E501

        :return: The keywords of this AuthorConnectL2RespModel.  # noqa: E501
        :rtype: str
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this AuthorConnectL2RespModel.

        Topic discussed by target author and connected authors  # noqa: E501

        :param keywords: The keywords of this AuthorConnectL2RespModel.  # noqa: E501
        :type: str
        """

        self._keywords = keywords

    @property
    def authors(self):
        """Gets the authors of this AuthorConnectL2RespModel.  # noqa: E501

        Authors most similar to target author based on target author discussions  # noqa: E501

        :return: The authors of this AuthorConnectL2RespModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors):
        """Sets the authors of this AuthorConnectL2RespModel.

        Authors most similar to target author based on target author discussions  # noqa: E501

        :param authors: The authors of this AuthorConnectL2RespModel.  # noqa: E501
        :type: list[str]
        """

        self._authors = authors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorConnectL2RespModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorConnectL2RespModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
