# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://www.sumup.ai/apis/#nucleus-documentation  # noqa: E501

    OpenAPI spec version: v4.0.9
    Contact: info@sumup.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TopicContrastL22RespModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'coefs': 'list[float]',
        'intercept': 'float',
        'keywords': 'list[str]'
    }

    attribute_map = {
        'coefs': 'coefs',
        'intercept': 'intercept',
        'keywords': 'keywords'
    }

    def __init__(self, coefs=None, intercept=None, keywords=None):  # noqa: E501
        """TopicContrastL22RespModel - a model defined in Swagger"""  # noqa: E501

        self._coefs = None
        self._intercept = None
        self._keywords = None
        self.discriminator = None

        if coefs is not None:
            self.coefs = coefs
        if intercept is not None:
            self.intercept = intercept
        if keywords is not None:
            self.keywords = keywords

    @property
    def coefs(self):
        """Gets the coefs of this TopicContrastL22RespModel.  # noqa: E501

        Trained coefs of the classifier  # noqa: E501

        :return: The coefs of this TopicContrastL22RespModel.  # noqa: E501
        :rtype: list[float]
        """
        return self._coefs

    @coefs.setter
    def coefs(self, coefs):
        """Sets the coefs of this TopicContrastL22RespModel.

        Trained coefs of the classifier  # noqa: E501

        :param coefs: The coefs of this TopicContrastL22RespModel.  # noqa: E501
        :type: list[float]
        """

        self._coefs = coefs

    @property
    def intercept(self):
        """Gets the intercept of this TopicContrastL22RespModel.  # noqa: E501

        Trained intercept of the classifier  # noqa: E501

        :return: The intercept of this TopicContrastL22RespModel.  # noqa: E501
        :rtype: float
        """
        return self._intercept

    @intercept.setter
    def intercept(self, intercept):
        """Sets the intercept of this TopicContrastL22RespModel.

        Trained intercept of the classifier  # noqa: E501

        :param intercept: The intercept of this TopicContrastL22RespModel.  # noqa: E501
        :type: float
        """

        self._intercept = intercept

    @property
    def keywords(self):
        """Gets the keywords of this TopicContrastL22RespModel.  # noqa: E501

        Keywords best contrasting the two classes in the dataset  # noqa: E501

        :return: The keywords of this TopicContrastL22RespModel.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this TopicContrastL22RespModel.

        Keywords best contrasting the two classes in the dataset  # noqa: E501

        :param keywords: The keywords of this TopicContrastL22RespModel.  # noqa: E501
        :type: list[str]
        """

        self._keywords = keywords

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TopicContrastL22RespModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TopicContrastL22RespModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
