[tool.poetry]
name = "openapispecdiff"
version = "1.42.0"
description = "Difference between two OpenAPISpec files"
authors = ["Bala <balak@cloudvector.com>"]
# New attributes
license = "MIT"
readme = "README.md"
#homepage = "https://github.com/ArecaBay"
#repository = "https://github.com/ArecaBay"
keywords = ["openapispecdiff", "swaggerdiff", "swaggerplugin"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.5"
openapispecdiff = "*"

[tool.poetry.dev-dependencies]
pex = "*"

[tool.poetry.scripts]
openapidiff = 'openapispecdiff.OpenApiSpecDiff:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
