$schema: http://json-schema.org/draft-07/schema
title: Reveal.yaml Schema
description: The validator of Reveal.yaml
definitions:
  path:
    type: string
    pattern: ^(?:https?://)?(?:[\w.-]+/?)+
  sized:
    type: object
    minProperties: 1
    additionalProperties: false
    required: [src]
    properties:
      src:
        $ref: "#/definitions/path"
        title: Soure path
      width:
        title: Width
        type: [integer, string]
      height:
        title: Height
        type: [integer, string]
  img:
    $ref: "#/definitions/sized"
    properties:
      label:
        title: Image caption
        type: string
    title: Image
  slide:
    title: A slide
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      id:
        title: Custom section id
        type: string
      title:
        title: Single line Markdown level 2 title
        type: string
      doc:
        title: Multiline Markdown pargraph
        type: string
      include:
        $ref: "#/definitions/path"
        title: Include a Markdown file name from "templates", append after "doc" key
      math:
        title: Latex math without "$$" brackets
        type: string
      youtube:
        $ref: "#/definitions/sized"
        title: Youtube video
      embed:
        $ref: "#/definitions/sized"
        title: External resource like PDF
      img:
        title: Images
        anyOf:
          - $ref: "#/definitions/img"
          - type: array
            items: {$ref: "#/definitions/img"}
            minItems: 1
      fragment:
        title: Fragment option
        type: object
        minProperties: 1
        additionalProperties: false
        properties:
          math: {type: string}
          img: {type: string}
          youtube: {type: string}
          embed: {type: string}
  hslide:
    $ref: "#/definitions/slide"
    properties:
      sub:
        title: Vertical slides
        anyOf:
          - $ref: "#/definitions/slide"
          - type: array
            items: {$ref: "#/definitions/slide"}
            minItems: 1
type: object
required: [nav]
properties:
  lang:
    title: Page language
    type: string
    default: en
  title:
    title: Page title, default is same as first page
    type: string
  description:
    title: Page description
    type: string
  author:
    title: Page author
    type: string
  watermark:
    $ref: "#/definitions/path"
    title: Watermark source
  watermark-size:
    title: Source width
    type: [integer, string]
  outline:
    title: Outline page under first column with depth
    type: integer
    default: 0
    maximum: 2
    minimum: 0
  theme:
    title: Reveal.js theme
    type: string
    default: serif
  code-theme:
    title: Highlight theme
    type: string
    default: zenburn
  icon:
    $ref: "#/definitions/path"
    title: Icon path
    default: img/icon.png
  default-style:
    title: Use default style
    type: boolean
    default: true
  extra-style:
    $ref: "#/definitions/path"
    title: Extra CSS style path in "templates"
  nav-mode:
    title: Reveal navigation mode option
    type: string
  show-arrows:
    title: Show control arrows
    type: boolean
    default: true
  center:
    title: Auto center the "doc"
    type: boolean
    default: true
  loop:
    title: Loop the slides
    type: boolean
    default: false
  history:
    title: Enable page history
    type: boolean
    default: true
  slide-num:
    title: Slide number style
    type: [boolean, string]
    default: c/t
  progress:
    title: Show progress bar
    type: boolean
    default: true
  mouse-wheel:
    title: Allow wheel control
    type: boolean
    default: false
  preview-links:
    title: Open a preview window for links
    type: boolean
    default: false
  transition:
    title: Transition mode
    type: string
    default: linear
  footer:
    $ref: "#/definitions/sized"
    title: Footer block
    properties:
      label:
        title: Footer title
        type: string
      link:
        $ref: "#/definitions/path"
        title: Link for footer title
  nav:
    title: Horizontal slides
    anyOf:
      - $ref: "#/definitions/hslide"
      - type: array
        items: {$ref: "#/definitions/hslide"}
        minItems: 1
