[tool.poetry]
name = "faststan"
version = "0.1.2"
description = "Build data streaming pipelines using faststan"
authors = ["gcharbon <guillaume.charbonnier@capgemini.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/faststan/"


[tool.poetry.dependencies]
python = "^3.7"
asyncio-nats-client = "^0.10.0"
asyncio-nats-streaming = "^0.4.0"
fastapi = "^0.61.0"
pydantic = "^1.6.1"
uvicorn = "^0.11.8"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
