theme: jekyll-theme-cayman
title: wot
description: A software package for analyzing snapshots of developmental processes
repository: broadinstitute/wot
show_downloads: false
navbar_items:
  - title: Home
    url: /
  - title: Tutorial
    url: /tutorial
  - title: Command Line
    url: /cli_documentation
  - title: File Formats
    url: /file_formats
  - title: Citing
    url: /citing_wot
  - title: Source Code
    url: /source_code
