# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pulpcore.client.pulp_2to3_migration
from pulpcore.client.pulp_2to3_migration.models.inline_response200 import InlineResponse200  # noqa: E501
from pulpcore.client.pulp_2to3_migration.rest import ApiException

class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse200
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pulpcore.client.pulp_2to3_migration.models.inline_response200.InlineResponse200()  # noqa: E501
        if include_optional :
            return InlineResponse200(
                count = 56, 
                next = '0', 
                previous = '0', 
                results = [
                    pulpcore.client.pulp_2to3_migration.models.pulp_2to3_migration/migration_plan_read.pulp_2to3_migration.MigrationPlanRead(
                        pulp_href = '0', 
                        pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        plan = pulpcore.client.pulp_2to3_migration.models.plan.Plan(), )
                    ]
            )
        else :
            return InlineResponse200(
                count = 56,
                results = [
                    pulpcore.client.pulp_2to3_migration.models.pulp_2to3_migration/migration_plan_read.pulp_2to3_migration.MigrationPlanRead(
                        pulp_href = '0', 
                        pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        plan = pulpcore.client.pulp_2to3_migration.models.plan.Plan(), )
                    ],
        )

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
