[tool.poetry]
name = "honestybox-measurement"
version = "1.0.10"
description = "A framework for measuring things and producing structured results."
authors = [
    "James Stewart <james@amorphitec.io>",
    "Stuart Dines <me@stuartdines.com>",
    "James Johnson <james.johnston@honestybox.com.au>"
]
maintainers = [
    "Honesty Box <engineering@honestybox.com.au>",
]
packages = [
    { include = "measurement" },
]
repository = "https://github.com/honesty-box/honestybox-measurement/"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5, <4"
validators = "^0.13.0"
dataclasses = {version = "^0.6.0", python = "^3.6.0"}
six = "^1.12"
speedtest-cli = "^2.1"
requests = "^2.23.0"
statistics = "^1.0.3"
youtube_dl = "^2020.6.16"
scapy = {version = "^2.4.4-rc.2", allow-prereleases = true}
[tool.poetry.dev-dependencies]
pytest = "^3.0"
tox = "^3.13"
flake8 = "^3.7"
isort = "^4.3"
pytest-cov = "^2.7"
black = {version = "^19.10b0", allow-prereleases = true, python = ">=3.6"}
bandit = "^1.6.2"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
skipsdist = true
envlist = py35,py36,py37,py38

[gh-actions]
python =
    3.5: py35
    3.6: py36
    3.7: py37
    3.8: py38, mypy

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest --cov
"""
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

