[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "prometheus-ecs-discoverer"
version = "3.1.1"
description = "Prometheus Service Discovery for AWS ECS"
authors = ["Tim Schwenke <tim.schwenke+trallnag@protonmail.ch>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/trallnag/prometheus-ecs-discoverer"
keywords = ["prometheus", "discovery", "aws", "ecs", "metrics"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: System :: Monitoring',
]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.14.23"
prometheus-client = "^0.8.0"
loguru = "^0.5.1"
prettyprinter = "^0.18.0"
dynaconf = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8"
black = "^19.10b0"
requests = "^2.24.0"
pytest-cov = "^2.10.0"
moto = "^1.3.14"
rope = "^0.17.0"
isort = "^5.2.2"

[tool.black]
line-length = 90
exclude = "tests/test_discovery_integration_data.py"
