# Generated by Django 2.1.7 on 2020-07-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cep_tipo_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cep',
            old_name='rua_cep',
            new_name='endereco_cep',
        ),
        migrations.AddField(
            model_name='cep',
            name='endereco_comp_cep',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
