[tool.poetry]
name = "mhealthlab-client"
version = "0.7.0"
description = "Client to download and decrypt data for lab projects of mhealthgroup.org"
authors = ["Qu Tang <tang.q@northeastern.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.0"
pyzipper = "^0.3.1"
outdated = "^0.2.0"
pysftp = "^0.2.9"
arus = "^1.1.12"
arus-muss = "^0.1.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.2"
pytest = "^5.4.3"


[tool.poetry.scripts]
mhlab = 'mhealthlab_client.mhlab:mhlab'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
