
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T12:07:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "afcb57ce9681653fb41d0398188a694482f6ee92",
 "version": "v0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
