[tool.poetry]
name = "xbrief"
version = "0.0.6"
description = "pretty print"
authors = ["Hoyeung Wong <hoyeungw@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aryth = ">=0.0.5"
intype = ">=0.0.2"
ject = ">=0.0.1"
palett = ">=0.0.4"
veho = ">=0.0.4"
texting = ">=0.0.3"

[tool.poetry.dev-dependencies]

[build-syste]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
