# Generated by Django 2.1.7 on 2020-08-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200824_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='informacao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
