order:
  - query_one.sql
  - query_two.sql


# Project variables can be rendered in SQL as follows: {{ foo }}
project_variables:
  foo: bar



# Connection variables can be rendered in SQL as follows: {{ c.foo }}
connection_variables:
  connection_name1:
    foo: bar
  connection_name2:
    foo: barbar


# Environment variables can be rendered in SQL as follows: {{ e.foo }}
environment_variables:
  dev:
    foo: devbar
  prod:
    foo: prodbar
