
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-21T17:31:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1624fcd58b873e6c1629a3b00c5cb588b724ce3",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
