
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T17:28:25+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fad35969cc543de9178ef42043984c5ea71a62a2",
 "version": "1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
