
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T13:02:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c81083b9008f818e4c7064e9d39cf9e9a8ac570",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
