
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-18T17:55:08.151910",
 "dirty": false,
 "error": null,
 "full-revisionid": "c251ff410183eed47b744f2250424aa1a4708575",
 "version": "0.4.0.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
