
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-24T20:52:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "49a67e76fa220fffa165d6e7cd85eb7c56cf5837",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
