# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://www.sumup.ai/apis/#nucleus-documentation  # noqa: E501

    OpenAPI spec version: v4.0.9
    Contact: info@sumup.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FilePropertyModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filename': 'str',
        'size': 'int'
    }

    attribute_map = {
        'filename': 'filename',
        'size': 'size'
    }

    def __init__(self, filename=None, size=None):  # noqa: E501
        """FilePropertyModel - a model defined in Swagger"""  # noqa: E501

        self._filename = None
        self._size = None
        self.discriminator = None

        if filename is not None:
            self.filename = filename
        if size is not None:
            self.size = size

    @property
    def filename(self):
        """Gets the filename of this FilePropertyModel.  # noqa: E501

        Filename of the file uploaded  # noqa: E501

        :return: The filename of this FilePropertyModel.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this FilePropertyModel.

        Filename of the file uploaded  # noqa: E501

        :param filename: The filename of this FilePropertyModel.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def size(self):
        """Gets the size of this FilePropertyModel.  # noqa: E501

        File size in bytes of the file uploaded  # noqa: E501

        :return: The size of this FilePropertyModel.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this FilePropertyModel.

        File size in bytes of the file uploaded  # noqa: E501

        :param size: The size of this FilePropertyModel.  # noqa: E501
        :type: int
        """

        self._size = size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilePropertyModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilePropertyModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
