
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d96fed990279fcd272cc5ada005d07c85b104ce5",
 "version": "2.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
