sudo: false
dist: xenial
language: python
install:
      - pip install tox
script:
      - tox
matrix:
    include:
        - env: TOXENV=pep8
        - python: 3.7
          env: TOXENV=placement
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
        - python: 3.5
          env: TOXENV=py35-pytest
        - python: 3.6
          env: TOXENV=py36-pytest
        - python: 3.7
          env: TOXENV=py37-pytest
        - python: 3.7
          env: TOXENV=py37-failskip
        - python: 3.7
          env: TOXENV=py37-limit
        - python: 3.7
          env: TOXENV=py37-prefix

notifications:
      irc: "chat.freenode.net#gabbi"
