[tool.poetry]
name = "a2wsgi"
version = "1.0.1"
description = "Convert WSGI app to ASGI app or ASGI app to WSGI app."
authors = ["abersheeran <me@abersheeran.com>"]
readme = "README.md"
license = "Apache-2.0"

homepage = "https://github.com/abersheeran/a2wsgi"
repository = "https://github.com/abersheeran/a2wsgi"

classifiers=[
    "Programming Language :: Python :: 3",
]

packages = [
    { include = "a2wsgi" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.1"
mypy = "^0.770"
black = "^19.10b0"
pytest = "^5.4.1"
pytest-asyncio = "^0.11.0"
pytest-cov = "^2.8.1"
httpx = {version = "^0.13.0-alpha.1", allow-prereleases = true}
uvicorn = "^0.11.5" # benchmark
asgiref = "^3.2.7" # benchmark

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
