# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://www.sumup.ai/apis/#nucleus-documentation  # noqa: E501

    OpenAPI spec version: v4.0.9
    Contact: info@sumup.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.doc_classify_resp_model import DocClassifyRespModel  # noqa: E501
from nucleus_api.rest import ApiException


class TestDocClassifyRespModel(unittest.TestCase):
    """DocClassifyRespModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocClassifyRespModel(self):
        """Test DocClassifyRespModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.doc_classify_resp_model.DocClassifyRespModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
