# This file is part of CoVeriTeam, a tool for on-demand composition of cooperative verification systems:
# https://gitlab.com/sosy-lab/software/coveriteam
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

imports: 
  - !include cpachecker.yml
  - !include verifier_resource.yml
actor_name: cpa-seq
options: ['-svcomp20', '-heap', '10000M', '-benchmark', '-timelimit', '900 s']
format_version: '1.1'
