# Generated by Django 2.1.7 on 2020-07-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0006_auto_20200716_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True},
        ),
    ]
