#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['stockmarket']

package_data = \
{'': ['*']}

install_requires = \
['cryptoxlib-aio==3.2.1']

setup(name='stockmarket',
      version='0.0.1',
      description='Get live stockmarket and crypto market datafeeds as Python objects in just a few lines of code!',
      author='Matt Gosden',
      author_email='mdgosden@gmail.com',
      url='https://github.com/ttamg/stockmarket',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
