[tool.poetry]
name = "quaternionic"
version = "0.1.0"
description = "Interpret numpy arrays as quaternionic arrays with numba acceleration"
readme = "README.md"
license = "MIT"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]
homepage = "https://github.com/moble/quaternionic"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.13"
scipy = "^1.0"
numba = "^0.50"
importlib-metadata = {version = "^1.0", python = "<3.8"}
mkdocs = {version = "^1.1.2", optional = true}
mktheapidocs = {extras = ["plugin"], version = "^0.2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.10.1"
mkdocs = "^1.1.2"
mktheapidocs = {extras = ["plugin"], version = "^0.2.0"}
black = "^19.10b0"

[tool.poetry.extras]
mkdocs = ["mkdocs"]
mktheapidocs = ["mktheapidocs"]

[tool.black]
line-length = 120
target-version = ['py36']

[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ".* build dist *.egg-info install ENV"
addopts = "-v --tb=short --doctest-glob='' --cov --cov-branch --cov-report html"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
