[tool.poetry]
name = "yellowbox"
version = "0.0.2a"
description = ""
authors = ["biocatch ltd"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/biocatchltd/yellowbox"

[tool.poetry.dependencies]
python = "^3.7"
docker = "^4.2.0"
yaspin = "^1.0.0"

redis = {version="^3.5.3", optional=true}
pika = {version="^1.1.0", optional=true}
kafka-python = {version="^2.0.1", optional=true}

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[tool.poetry.extras]
redis = ["redis"]
rabbit = ["pika"]
kafka = ["kafka-python"]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
