# Generated by Django 2.1.7 on 2020-07-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': False},
        ),
    ]
