active_rule: ''
rules:
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  _fields: []
  auto_fix: false
  description: Rule used to manage naming of assets
  expression: '{project}_{asset_type}_{asset_id}_{description}'
  iterator_format: '@'
  name: asset
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  _fields: []
  auto_fix: false
  description: Rule used to rename asset files
  expression: '{asset_name}'
  iterator_format: '@'
  name: asset_file
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: ''
  expression: '{description}'
  iterator_format: '@'
  name: light_rig
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: Defines the name of DCC nodes
  expression: '{description}_{side}_{node_type}_{id}'
  iterator_format: '####'
  name: node
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: Root node for modeling
  expression: '{root_group}'
  iterator_format: '@'
  name: root_group
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: Geometry group for modeling
  expression: '{geo_group}'
  iterator_format: '@'
  name: geo_group
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: High version for modeling
  expression: '{high_group}'
  iterator_format: '@'
  name: high_group
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: Proxy version for modeling
  expression: '{proxy_group}'
  iterator_format: '@'
  name: proxy_group
- _Serializable_classname: Rule
  _Serializable_version: '1.0'
  auto_fix: false
  description: Defines the name used by asset proxy geometries
  expression: '{proxy_geo}_{side}_{geo}_{id}'
  iterator_format: '####'
  name: proxy_geo
template_tokens:
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Name of the texture.
  name: texture_name
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Type of the file.
  name: file_type
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Extension of the file.
  name: file_extension
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Type of the asset.
  name: asset_type
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Name of the asset.
  name: asset_name
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Name of the sequence. This name must be unique.
  name: sequence_name
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Version folder of the file.
  name: version_folder
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Path where project is located in user local disk.
  name: project_path
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Type of the folder.
  name: folder_type
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Path where asset is located.
  name: asset_path
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Path where assets are located
  name: assets_path
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Name of the light rig
  name: light_rig_name
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Unique ID number of the Artella Project
  name: project_id_number
- _Serializable_classname: TemplateToken
  _Serializable_version: '1.0'
  description: Unique ID of the Artella Project
  name: project_id
templates:
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: asset_path
  pattern: '{@project_path}/Assets/{asset_type}/{asset_name}'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: rig
  pattern: '{@asset_path}/{version_folder}/rig/{asset_name}.{file_extension}'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: model
  pattern: '{@asset_path}/{version_folder}/model/{asset_name}.{file_extension}'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: shading
  pattern: '{@asset_path}/{version_folder}/shading/{asset_name}.{file_extension}'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: textures
  pattern: '{@asset_path}/{version_folder}/textures'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: groom
  pattern: '{@asset_path}/{version_folder}/groom'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: lightrig
  pattern: '{@lightrigs}/{light_rig_name}'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: lightrigs
  pattern: '{@project_path}/Assets/LightSets'
- _Serializable_classname: Template
  _Serializable_version: '1.0'
  name: project_path
  pattern: $PLOTTWIST_PROJECT
tokens:
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: Description of the asset.
  items: {}
  name: description
  override_value: ''
  values:
    key: []
    value: []
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: 'The format of the id


    #: Id with a unique numeric value

    @: Id with an alphabetic value (lowercase)

    @^: Id with an alphabetic value (upperase)


    NOTE: @ key do not need multiples keys ( @@, @@@) beause the system\nautomatically
    will add double alphabetic characters if we pass the ''z'' character (a...z, aa,
    ab, ac, ad ...)'
  items: {}
  name: id
  override_value: ''
  values:
    key:
    - iterator
    value:
    - '#'
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: ''
  items: {}
  name: asset_type
  override_value: ''
  values:
    key:
    - props
    - backgroundelements
    - characters
    value:
    - PRP
    - BGE
    - CHR
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: Short name of the current project
  items: {}
  name: project
  override_value: ''
  values:
    key: []
    value: []
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: Unique number for each one of the assets inside a category
  items: {}
  name: asset_id
  override_value: ''
  values:
    key: []
    value: []
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: Complete name of the asset
  items: {}
  name: asset_name
  override_value: ''
  values:
    key: []
    value: []
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: ''
  name: side
  override_value: ''
  values:
    key:
    - center
    - right
    - left
    value:
    - c
    - r
    - l
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: ''
  name: rule_name
  override_value: ''
  values:
    key:
    - rule_name
    value:
    - ''
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: ''
  name: node_type
  override_value: ''
  values:
    key: []
    value: []
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: ''
  name: root_group
  override_value: ''
  values:
    key:
    - root
    value:
    - root
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: ''
  name: geo_group
  override_value: ''
  values:
    key:
    - geo
    value:
    - geo
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: ''
  name: high_group
  override_value: ''
  values:
    key:
    - high
    value:
    - high
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 1
  description: ''
  name: proxy_group
  override_value: ''
  values:
    key:
    - proxy
    value:
    - proxy
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: ''
  name: proxy_geo
  override_value: ''
  values:
    key:
    - proxy
    value:
    - proxy
- _Serializable_classname: Token
  _Serializable_version: '1.0'
  default: 0
  description: ''
  name: geo
  override_value: ''
  values:
    key:
    - geo
    value:
    - geo
