rows = [
    ('coldness의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/coldness_nz'),
    ('coldness의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/coldness_oz'),
    ('FD의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/FD_nz'),
    ('FD의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/FD_oz'),
    ('GSL의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/GSL_nz'),
    ('GSL의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/GSL_oz'),
    ('HW의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/HW_nz'),
    ('HW의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/HW_oz'),
    ('ID의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/ID_nz'),
    ('ID의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/ID_oz'),
    ('ins의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/ins_nz'),
    ('ins의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/ins_oz'),
    ('prcp_10davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_10davg_nz'),
    ('prcp_10davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_10davg_oz'),
    ('prcp_5davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_5davg_nz'),
    ('prcp_5davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_5davg_oz'),
    ('prcp의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_nz'),
    ('prcp의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/prcp_oz'),
    ('R80mm의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/R80mm_nz'),
    ('R80mm의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/R80mm_oz'),
    ('SDII의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/SDII_nz'),
    ('SDII의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/SDII_oz'),
    ('sunshine_10davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_10davg_nz'),
    ('sunshine_10davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_10davg_oz'),
    ('sunshine_5davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_5davg_nz'),
    ('sunshine_5davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_5davg_oz'),
    ('sunshine의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_nz'),
    ('sunshine의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/sunshine_oz'),
    ('SU의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/SU_nz'),
    ('SU의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/SU_oz'),
    ('tavg_10davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_10davg_nz'),
    ('tavg_10davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_10davg_oz'),
    ('tavg_5davg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_5davg_nz'),
    ('tavg_5davg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_5davg_oz'),
    ('tavg의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_nz'),
    ('tavg의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tavg_oz'),
    ('tmax의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tmax_nz'),
    ('tmax의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tmax_oz'),
    ('tmin의 평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tmin_nz'),
    ('tmin의 과거평년 대비 변화량(σ)', 'daily', '/data/estimation/change/tmin_oz'),
    ('TR의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/TR_nz'),
    ('TR의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/TR_oz'),
    ('warmth의 평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/warmth_nz'),
    ('warmth의 과거평년 대비 변화량(σ)', 'yearly', '/data/estimation/change/warmth_oz'),
    ('일사량(MJ/㎡)', 'daily', '/data/estimation/climate/ins'),
    ('일사량의 월 평균(MJ/㎡)', 'monthly', '/data/estimation/climate/ins_mavg'),
    ('일사량의 월 최대(MJ/㎡)', 'monthly', '/data/estimation/climate/ins_mmax'),
    ('일사량의 월 최소(MJ/㎡)', 'monthly', '/data/estimation/climate/ins_mmin'),
    ('일사량의 월 합계(MJ/㎡)', 'monthly', '/data/estimation/climate/ins_msum'),
    ('ins의 연도별 평균(MJ/㎡)', 'yearly', '/data/estimation/climate/ins_yavg'),
    ('ins의 연도별 최고(MJ/㎡)', 'yearly', '/data/estimation/climate/ins_ymax'),
    ('ins의 연도별 최저(MJ/㎡)', 'yearly', '/data/estimation/climate/ins_ymin'),
    ('ins의 연도별 합계(MJ/㎡)', 'yearly', '/data/estimation/climate/ins_ysum'),
    ('강수량(mm)', 'daily', '/data/estimation/climate/prcp'),
    ('10일 이동평균강수량(mm/days)', 'daily', '/data/estimation/climate/prcp_10davg'),
    ('5일 이동평균강수량(mm/days)', 'daily', '/data/estimation/climate/prcp_5davg'),
    ('강수량의 월 평균(mm)', 'monthly', '/data/estimation/climate/prcp_mavg'),
    ('강수량의 월 최고(mm)', 'monthly', '/data/estimation/climate/prcp_mmax'),
    ('강수량의 월 최소(mm)', 'monthly', '/data/estimation/climate/prcp_mmin'),
    ('강수량의 월 누적(mm)', 'monthly', '/data/estimation/climate/prcp_msum'),
    ('prcp의 연도별 평균(mm)', 'yearly', '/data/estimation/climate/prcp_yavg'),
    ('prcp의 연도별 최고(mm)', 'yearly', '/data/estimation/climate/prcp_ymax'),
    ('prcp의 연도별 최소(mm)', 'yearly', '/data/estimation/climate/prcp_ymin'),
    ('prcp의 연도별 합계(mm)', 'yearly', '/data/estimation/climate/prcp_ysum'),
    ('습도(%)', 'daily', '/data/estimation/climate/rhum'),
    ('습도의 월 평균(mm)', 'monthly', '/data/estimation/climate/rhum_mavg'),
    ('습도의 월 최고(mm)', 'monthly', '/data/estimation/climate/rhum_mmax'),
    ('습도의 월 최소(mm)', 'monthly', '/data/estimation/climate/rhum_mmin'),
    ('습도의 월 합계(mm)', 'monthly', '/data/estimation/climate/rhum_msum'),
    ('일조시간(hr)', 'daily', '/data/estimation/climate/sunshine'),
    ('10일 이동평균일조시간(hr/day)', 'daily', '/data/estimation/climate/sunshine_10davg'),
    ('5일 이동평균일조시간(hr/day)', 'daily', '/data/estimation/climate/sunshine_5davg'),
    ('일조시간의 월 평균(hr)', 'monthly', '/data/estimation/climate/sunshine_mavg'),
    ('일조시간의 월 최대(hr)', 'monthly', '/data/estimation/climate/sunshine_mmax'),
    ('일조시간의 월 최소(hr)', 'monthly', '/data/estimation/climate/sunshine_mmin'),
    ('일조시간의 월 합계(hr)', 'monthly', '/data/estimation/climate/sunshine_msum'),
    ('sunshine의 연도별 평균(hr)', 'yearly', '/data/estimation/climate/sunshine_yavg'),
    ('sunshine의 연도별 최대(hr)', 'yearly', '/data/estimation/climate/sunshine_ymax'),
    ('sunshine의 연도별 최소(hr)', 'yearly', '/data/estimation/climate/sunshine_ymin'),
    ('sunshine의 연도별 합계(hr)', 'yearly', '/data/estimation/climate/sunshine_ysum'),
    ('평균기온(℃)', 'daily', '/data/estimation/climate/tavg'),
    ('10일 이동평균기온(℃/day)', 'daily', '/data/estimation/climate/tavg_10davg'),
    ('5일 이동평균기온(℃/day)', 'daily', '/data/estimation/climate/tavg_5davg'),
    ('평균기온의 월 평균(℃)', 'monthly', '/data/estimation/climate/tavg_mavg'),
    ('평균기온의 월 최고(℃)', 'monthly', '/data/estimation/climate/tavg_mmax'),
    ('평균기온의 월 최소(℃)', 'monthly', '/data/estimation/climate/tavg_mmin'),
    ('평균기온의 월 합계(℃)', 'monthly', '/data/estimation/climate/tavg_msum'),
    ('tavg의 연도별 평균(℃)', 'yearly', '/data/estimation/climate/tavg_yavg'),
    ('tavg의 연도별 최고(℃)', 'yearly', '/data/estimation/climate/tavg_ymax'),
    ('tavg의 연도별 최저(℃)', 'yearly', '/data/estimation/climate/tavg_ymin'),
    ('최고기온(℃)', 'daily', '/data/estimation/climate/tmax'),
    ('최고기온의 월 평균(℃)', 'monthly', '/data/estimation/climate/tmax_mavg'),
    ('최고기온의 월 최고(℃)', 'monthly', '/data/estimation/climate/tmax_mmax'),
    ('최고기온의 월 최소(℃)', 'monthly', '/data/estimation/climate/tmax_mmin'),
    ('최고기온의 월 합계(℃)', 'monthly', '/data/estimation/climate/tmax_msum'),
    ('tmax의 연도별 평균(℃)', 'yearly', '/data/estimation/climate/tmax_yavg'),
    ('tmax의 연도별 최고(℃)', 'yearly', '/data/estimation/climate/tmax_ymax'),
    ('tmax의 연도별 최소(℃)', 'yearly', '/data/estimation/climate/tmax_ymin'),
    ('최저기온(℃)', 'daily', '/data/estimation/climate/tmin'),
    ('최저기온의 월 평균(℃)', 'monthly', '/data/estimation/climate/tmin_mavg'),
    ('최저기온의 월 최고(℃)', 'monthly', '/data/estimation/climate/tmin_mmax'),
    ('최저기온의 월 최소(℃)', 'monthly', '/data/estimation/climate/tmin_mmin'),
    ('최저기온의 월 합계(℃)', 'monthly', '/data/estimation/climate/tmin_msum'),
    ('tmin의 연도별 평균(℃)', 'yearly', '/data/estimation/climate/tmin_yavg'),
    ('tmin의 연도별 최고(℃)', 'yearly', '/data/estimation/climate/tmin_ymax'),
    ('tmin의 연도별 최소(℃)', 'yearly', '/data/estimation/climate/tmin_ymin'),
    ('한랭지수(℃)', 'yearly', '/data/estimation/index/coldness'),
    ('서리일수(days)', 'yearly', '/data/estimation/index/FD'),
    ('식물성장기간(days)', 'yearly', '/data/estimation/index/GSL'),
    ('호우지수(prcp >= 80mm)', 'daily', '/data/estimation/index/hvrain'),
    ('호우지수의 월별 합계(days)', 'monthly', '/data/estimation/index/hvrain_msum'),
    ('호우지수의 연도별 합계(days)', 'yearly', '/data/estimation/index/hvrain_ysum'),
    ('폭염일수(days)', 'yearly', '/data/estimation/index/HW'),
    ('결빙일수(days)', 'yearly', '/data/estimation/index/ID'),
    ('호우일수(days)', 'yearly', '/data/estimation/index/R80mm'),
    ('강수강도(mm/days)', 'yearly', '/data/estimation/index/SDII'),
    ('여름일수(days)', 'yearly', '/data/estimation/index/SU'),
    ('한랭지수의 월 합계(℃)', 'monthly', '/data/estimation/index/sum_coldness'),
    ('온량지수의 월 합계(℃)', 'monthly', '/data/estimation/index/sum_warmth'),
    ('폭우지수(prcp >= prcp_ysum_navg*0.1)', 'daily', '/data/estimation/index/torrain'),
    ('폭우지수의 월별 합계(days)', 'monthly', '/data/estimation/index/torrain_msum'),
    ('폭우지수의 연도별 합계(days)', 'yearly', '/data/estimation/index/torrain_ysum'),
    ('열대야일수(days)', 'yearly', '/data/estimation/index/TR'),
    ('온량지수(℃)', 'yearly', '/data/estimation/index/warmth'),
    ('일별 강수량(mm)', 'daily', '/data/estimation/reanalysis/corr_prec'),
    ('corr_prec의 월별 합계(mm)', 'monthly', '/data/estimation/reanalysis/corr_prec_sum'),
    ('e의 일별 평균(hPa)', 'daily', '/data/estimation/reanalysis/e_avg'),
    ('e_avg의 월별 평균(hPa)', 'monthly', '/data/estimation/reanalysis/e_avg_avg'),
    ('smois의 일별 평균(㎡/㎡)', 'daily', '/data/estimation/reanalysis/smois_avg'),
    ('smois_avg의 월별 평균(㎡/㎡)', 'monthly', '/data/estimation/reanalysis/smois_avg_avg'),
    ('일별 일조시간(hr)', 'daily', '/data/estimation/reanalysis/sund'),
    ('sund의 월별 평균(hr)', 'monthly', '/data/estimation/reanalysis/sund_avg'),
    ('swdown의 일별 평균(W/㎡)', 'daily', '/data/estimation/reanalysis/swdown_avg'),
    ('swdown_avg의 월별 평균(W/㎡)', 'monthly', '/data/estimation/reanalysis/swdown_avg_avg'),
    ('t2의 일별 평균(℃)', 'daily', '/data/estimation/reanalysis/t2_avg'),
    ('t2_avg의 월별 평균(℃)', 'monthly', '/data/estimation/reanalysis/t2_avg_avg'),
    ('t2_avg의 월별 최고(℃)', 'monthly', '/data/estimation/reanalysis/t2_avg_max'),
    ('t2_avg의 월별 최저(℃)', 'monthly', '/data/estimation/reanalysis/t2_avg_min'),
    ('일별 2m 최고기온(℃)', 'daily', '/data/estimation/reanalysis/t2max'),
    ('t2max의 월별 평균(℃)', 'monthly', '/data/estimation/reanalysis/t2max_avg'),
    ('일별 2m 최저기온(℃)', 'daily', '/data/estimation/reanalysis/t2min'),
    ('t2min의 월별 평균(℃)', 'monthly', '/data/estimation/reanalysis/t2min_avg'),
    ('tslb의 일별 평균(℃)', 'daily', '/data/estimation/reanalysis/tslb_avg'),
    ('tslb_avg의 월별 평균(℃)', 'monthly', '/data/estimation/reanalysis/tslb_avg_avg'),
    ('tslb_avg의 월별 최고(℃)', 'monthly', '/data/estimation/reanalysis/tslb_avg_max'),
    ('tslb_avg의 월별 최소(℃)', 'monthly', '/data/estimation/reanalysis/tslb_avg_min'),
    ('tslb의 일별 최대(℃)', 'daily', '/data/estimation/reanalysis/tslb_max'),
    ('tslb의 일별 최소(℃)', 'daily', '/data/estimation/reanalysis/tslb_min'),
    ('ws2m의 일별 평균(m/s)', 'daily', '/data/estimation/reanalysis/ws2m_avg'),
    ('ws2m_avg의 월별 평균(m/s)', 'monthly', '/data/estimation/reanalysis/ws2m_avg_avg'),
    ('ws2m의 일별 최대(m/s)', 'daily', '/data/estimation/reanalysis/ws2m_max'),
    ('ws2m의 일별 최소(m/s)', 'daily', '/data/estimation/reanalysis/ws2m_min'),
]
