[tool.poetry]
name = "geo-parallel"
version = "0.1.5.5"
description = ""
authors = ["Artur"]
packages = [
    { include = "*" },
]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
