XXXXXXXX
XXXXXXXX
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
   XXXXXXX XX X

XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXX
XXXXXXXXXXXXX

    XXXXXXXXXXX XXXXX XXXX XX XXXXXXX XXXXXXX XX XXXXX XXXX XX XXXXXXXXXX
    XXXX XX XXXXXX XXXX XXXXX XXXXXXX XXX XXXXXX XXXXXXXXXX

    XX XXXXXXXXXXXX XXXXXX

       BBBB BBBBBBBBBBBB

       BBBBBBB

    XXXXXXXXX XXXXXXX

    XX XXXXXXXXXXXX XXXXXX

       BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXXXX XXX XXXXXX XXXXX XXXXXXXXX X XXXX XXXXXX

    XX XXXXXXXXXXXX XXXXXX

        XXXXXXX
            XXXXXXX XXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX
                BB BBBBBBBBBBBBB
                        XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX
                BBBB BBBBBBBBBB
                        XXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXX
                BBBBB
                    XXXXXXX XXXX
                FFFF
                    XXXXXXX XXXX
                FFFF
            XXXX
        BBBBBB
            XXXXXXX XXXXXXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX
                XX XXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                            XXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBBBB
                            XXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXX
                    BBBB
                           XXX XXXXXXXXX XXXX XXX XXXXXXXXX
                        
                    BBBBB
                XXXX
            XXXX
        BBBBBB

XXXX
XXXX

XXXX XXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX X XXXXXXXXXXXXXXXXXXX XXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX

XXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXX X
    XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXX XXXXXXXXXXX XXXXX X XXXXXXX XXXXXXXX

XXXX XXXX XXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXX XXXXX X XXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX
    XXXXX XXXXXXXXXXX XXXXX X XXXXXXX XXXX XXXX