XXXXXXXXXXXX
XXXXXXXXXXXX

XXX XXXXXX XXX XXXXXXX XXXXXX

XXXXXXXXX
XXXXXXXXX

XXXX XXXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXX XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXX
    XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX X XXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XX XXXXXXXX

XXXXXXXX XXXX
XXXXXXXXXXXXX

XXXXXXXXXXX XXXXX XXXX XX XXXXXXX XXXXXXX XX XXXXX XXXX XX XXXXXXXXXX

XX XXXXXXXXXXXX XXXXXX

   BBBB BBBBBBBBB

   BBBBBBBBBBBBB

XXXXXXXXX XXXXXXX

XX XXXXXXXXXXXX XXXXXX

   BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXX XXX XXXXXX XXXXXX XXXXXXXXXX

XX XXXXXXXXXXXX XXXXXX

    XXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBB
            XXXX
                XX XXXXXXXXXXXX
            XXXXX
        BBBBBB
    XXXXX


XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX

XXXXX XXXXXX XXXXXX
XXXXXXXXXXXXXXXXXXX
XXX XXXXXXX
    XXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXXXX XXXXXX

    BBB BBBB BB BBBBBBBBB
        BB BBBBBBBBBB
            XXXX XXXXXXX
        BBBBB
        XXXXXXX
        XXX
            
        XXXX
    BBBBBB

XXXXX XXXXXX XXXXXX
XXXXXXXXXXXXXXXXXXX
XXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX

XX XXXXXXXXXXXX XXXXXX

    XXXXXXXXX
    BB BBBBBBBBBBB
        XXXXXXX
    BBBBB
    XXXXXXXXXXXXXXX XXXX
    BB BBBBBBBBBB
        XXXX XXXXXX XXXXXXX
    BBBBB
    FFFF
    XXXXXXXXXXXX X 

XXXX XXXXXX XXXXXX
XXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXX XXXX
    XXXXXXX XXXXXXXXX
    XXXXXXXXXX XXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXX XXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXX XXXXXXXX
    XXXXXXXXXXX XXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXX XXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXX XXXX
    XXXXXXXXXX XXXXXX
    XXXXXX XXX
    XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX X XXXXXXXXXX
    XXXXXXXX XXXXXXXXXX
    XXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXX


XXXXXXXX XXXX
XXXXXXXXXXXXX

    XXXXXXXXXXX XXXXX XXXX XX XXXXXXX XXXXXXX XX XXXXX XXXX XX XXXXXXXXXX

    XX XXXXXXXXXXXX XXXXXX

       BBBB BBBBBBBBB

       BBBBBBBBB

    XXXXXXXXX XXXXXXX

    XX XXXXXXXXXXXX XXXXXX

       BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXXXX XXX XXXXXX XXXXXX XXXXXXX

    XX XXXXXXXXXXXX XXXXXX

        BBB BBBB BB BBBBBBBBB
            XXXXXX XXXXXXXX  XXXXXXXXX
            BB BBBBBBBBBB
                XXXX XXXXXXX
            BBBBB
            XXXXXXX
        BBBBBB

XXXX
XXXXXXXXX

XXXX XXXXXX XXXXX
XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXX
    XXXXXX XXX
    XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX X XXXXXXXXXX

XXXXXXXXXXX
XXXXXXXXXXX

XXXX XXXXXX XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXX XXXXX X XXXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX XXXXX X XXXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXX
    XXXXXXXX XXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX X XXXXXXXXXX