
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-20T03:44:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ff70a7132cae3ecca838ae7f5693c2cc1feb8ba",
 "version": "1.13.0.post.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
