
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-25T14:37:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "766deb6b30b3d762990a1822da075158c5768abd",
 "version": "0.13.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
