
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-26T16:58:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ced5d24777d3a0db0256295d0719a2da7122c85a",
 "version": "0.81.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
