# Generated by Django 2.2.7 on 2020-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_user_bio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsored_text',
            field=models.TextField(default='Sponsored by'),
        ),
    ]
