# Generated by Django 2.1.7 on 2020-07-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20200713_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='perfilgrupo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='perfillogin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='perfilpontofuncao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pontofuncao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='versao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='versaoitem',
            options={'managed': True},
        ),
    ]
