[tool.poetry]
name = "autohooks-plugin-pdoc"
version = "0.1.2"
description = "An autohooks plugin for python documentation via pdoc"
authors = ["Craig de Gouveia <craig.degouveia@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/HughZurname/autohooks-plugin-pdoc"
repository = "https://github.com/HughZurname/autohooks-plugin-pdoc"
classifiers = [
  # Full list: https://pypi.org/pypi?%3Aaction=list_classifiers
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
  { include = "autohooks" },
  { include = "CHANGELOG.md", format = "sdist"},
  { include = "RELEASE.md", format = "sdist"},
  { include = "poetry.lock", format = "sdist"},
  { include = "poetry.toml", format = "sdist"},
]
keywords = [
  "git",
  "documentation",
  "hooks",
  "pdoc",
]

[tool.poetry.dependencies]
python = "^3.7"
autohooks = ">=1.1"
pdoc = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autohooks-plugin-isort = "^1.0.0"
autohooks-plugin-pylint = "^1.2.0"
black = "^20.8b1"
autohooks-plugin-black = "^1.2.0"

[tool.autohooks]
mode = "poetry"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.pylint", "autohooks.plugins.isort"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
