apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd-server-argocd.apps.{{ cluster | default('testk') }}.{{ domain | default('karmalabs.com') }}
  dex.config: |
    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://api.{{ cluster | default('testk') }}.{{ domain | default('karmalabs.com') }}:6443
          clientID: system:serviceaccount:argocd:argocd-dex-server
          clientSecret: SECRET
          redirectURI: https://argocd-server-argocd.apps.{{ cluster | default('testk') }}.{{ domain | default('karmalabs.com') }}/api/dex/callback
          insecureCA: true
