[black]
args = ["--check"]
help = "Code formatter for python."
fast = true
test = true
strict = true

[black.format]
clear_args = true

[flake8]
args = ["--max-line-length=88", "--ignore=E203"]
help = "Code style checker for python."
fast = true
test = true
strict = true

[autoflake]
args = [
    "--in-place",
    "--recursive",
    "--expand-star-imports",
    "--remove-all-unused-imports"
]
help = "Remove unused imports and variables"
format = true
standard = false

# The isort problem
# =================
#
# Unfortunaly, "isort" is very effected by the environments it is running on in versions
# less than 5.0.
# This is causing a lot of problems when running isort using tox or in a virtual machine
# during CI/CD process.
#
# At the moment, "pylint" stricktly requries isort to be with version less than 5.0,
# which prevents us from using "isort".
#
# Once "pylint" will remove this requirement, we will return using isort.
#
#[isort]
#args = [
#    "--recursive",
#    "--multi-line=3",
#    "--trailing-comma",
#    "--force-grid-wrap=0",
#    "--use-parentheses",
#    "--lines=88",
#    "--check-only"
#]
#help = "Tool for sorting and cleaning python imports."
#fast = true
#test = true
#
#[isort.format]
#args = [
#    "--recursive",
#    "--multi-line=3",
#    "--trailing-comma",
#    "--force-grid-wrap=0",
#    "--use-parentheses",
#    "--lines=88"
#]

[mypy]
args = ["--ignore-missing-imports"]
help = "Validate types using mypy."
fast = true
test = true

[mypy.strict]
add_args = ["--strict"]

[pylint]
args = [
    "--ignore-imports=y",
    "--disable=C0203,C0330,C0411,E0401,E0611,E1130"
    ]
help = "Python code linter"

[pylint.strict]
args = ["--ignore-imports=y", "--disable=bad-continuation"]

[pylint.test]
add_args = [
    "--disable=C0103,C0114,C0115,C0116,C0204",
    "--disable=E1101,E1120,E1139",
    "--disable=R0801,R0902,R0903,R0904,R0913",
    "--disable=W0201,W0613,W0621"]

[bandit]
args = ["-r"]
help = "Python security checks tool."
strict = true

[bandit.test]
add_args = ["--skip=B101"]

[pydocstyle]
args = ["--ignore=D203,D212,D400,D401"]
help = "Tool for python docstring style enforcing"
test = false
strict = true