[tool.poetry]
name = "click-date-type"
version = "0.1.0"
description = "Date type parameter for click"
authors = ["Enrico Barzetti <enricobarzetti@gmail.com>"]
readme = 'README.rst'
homepage = 'https://github.com/enricobarzetti/click-date-type'

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.17.0"
isort = "^5.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
