
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.51.1'
version_full = 'c5f8505fb296ae3fc3867e1e257f28ea3423991a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

