language: python
sudo: required
dist: bionic    # Has SageMath 8.1
stages:
  - quick test
  - test
jobs:
  include:
  ##
  ## Quick test with Python 2 and 3 from conda-forge sagemath package
  ##
  - stage: quick test
    env: CACHE_NAME=conda CONDA_ENV=sage-cgf
    python: "2.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment-python2.yml || conda env update -n $CONDA_ENV --prune -f environment-python2.yml
    - conda activate $CONDA_ENV
    script:
    - "./.travis-quick-test.sh"
  - stage: quick test
    env: CACHE_NAME=conda-py3 CONDA_ENV=sage-cgf-py3
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment.yml || conda env update -n $CONDA_ENV --prune -f environment.yml
    - conda activate $CONDA_ENV
    script:
    - "./.travis-quick-test.sh"
  ##
  ## Full test with conda-forge sagemath package, deploy docs
  ##
  - stage: test
    env: CACHE_NAME=conda CONDA_ENV=sage-cgf DEPLOY_DOC_TO_DIRECTORY=doc/html
    python: "2.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment-python2.yml || conda env update -n $CONDA_ENV --prune -f environment-python2.yml
    - conda activate $CONDA_ENV
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash -x .travis-deploy-doc.sh
        on:
          branch: master
          repo: mkoeppe/cutgeneratingfunctionology
          condition: -r .travis_ci_gh_pages_deploy_key
  - env: CACHE_NAME=conda-py3 CONDA_ENV=sage-cgf-py3
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment.yml || conda env update -n $CONDA_ENV --prune -f environment.yml
    - conda activate $CONDA_ENV
  - env: CACHE_NAME=conda-py3-latestsage CONDA_ENV=sage-cgf-latestsage
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment-latestsage.yml || conda env update -n $CONDA_ENV --prune -f environment-latestsage.yml
    - conda activate $CONDA_ENV

  ##
  ## Test with Ubuntu sagemath package
  ##
  ## The following *almost* works, but the final "pip" install installs somewhere separate.
  ## This needs investigating; but Ubuntu bionic sage version is outdated anyway... so maybe not worth it.
  ## - env: CACHE_NAME=ubuntu-package
  ##   addons:
  ##     apt:
  ##       packages:
  ##         - sagemath
  ##         - python-sphinxcontrib.websupport

  ##
  ## Test with Sage binary packages
  ##
  - env: CACHE_NAME=latest SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=0
  - env: CACHE_NAME=older SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=1
  - env: CACHE_NAME=oldest SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=2

  ## Allowed failures.  Allow fail with latestsage, just in case someone breaks something there
  allow_failures:
  - env: CACHE_NAME=conda-py3-latestsage CONDA_ENV=sage-cgf-latestsage
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-conda-install.sh
    - conda env create -n $CONDA_ENV -f environment-latestsage.yml || conda env update -n $CONDA_ENV --prune -f environment-latestsage.yml
    - conda activate $CONDA_ENV
  ## More allowed failures.  Sage binary based runs often timeout while downloading the image.
  - env: CACHE_NAME=latest SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=0
  - env: CACHE_NAME=older SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=1
  - env: CACHE_NAME=oldest SAGE_SERVER=http://files.sagemath.org/linux/64bit/ SAGE_AGE=2
addons:
   apt:
     packages:
      # On 8.0 with trusty, Fortran compiler is needed.
      # Otherwise, numpy cannot be imported.
      # Also, optional package installs in .travis-install.sh will trigger build of sage gcc.
      - gfortran
install:
- source "./.travis-install.sh"
script:
- "./.travis-test.sh"
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/SageMath"
  - "$HOME/.cache/matplotlib"
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
after_success:
- openssl aes-256-cbc -K $encrypted_71e928c0b1a9_key -iv $encrypted_71e928c0b1a9_iv
  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d || true
