## This is a conda environment file.
## Use it as follows:
##
##    conda env create -f environment.yml
##
## See https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533
## or    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: sage-cgf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - sage=9.0
  - setuptools_scm
  - sphinx
  - sphinxcontrib-websupport
  - sphinxcontrib-bibtex
  - werkzeug<=0.16.1    # this version because of ImmutableDict:  https://stackoverflow.com/questions/60106527/importerror-cannot-import-name-immutabledict-error-when-installing-pgadmin4
  - lrslib
  - normaliz
  - boost-cpp      # For installing PyNormaliz
  - mathjax
  - pip
  - pip:
    - pynormaliz==2.8
    - sage-package
