[tool.poetry]
name = "sengen"
version = "0.1.0"
description = "Synthetic Sensor Data Generator"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "sympy"
sympy = "^1.6.2"
pandas = "^1.1.1"
matplotlib = "^3.3.1"
scipy = "^1.5.2"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
