[tool.poetry]
name = "mkkm_mr"
version = "0.2.5"
description = "MKKM-MR Python Implementation"
authors = ["Fma <fmakdemir@users.noreply.github.com>"]
license = "BSD-2-Clause"
repository = 'https://github.com/fmakdemir/mkkm-mr'
homepage = 'https://github.com/fmakdemir/mkkm-mr'
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "^1.19.1"
scipy = "^1.5.2"
cvxopt = "^1.2.5"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
h5py = "^2.10.0"
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
