name: cld2
mapping:
  af: afr
  am: amh
  ar: ara
  as: asm
  ay: aym
  az: aze
  ba: bak
  be: bel
  bg: bul
  bh: bho
  bn: ben
  bo: bod
  br: bre
  bs: bos
  ca: cat
  ceb: ceb
  chr: chr
  co: cos
  cs: ces
  cy: cym
  da: dan
  de: deu
  dv: div
  el: ell
  en: eng
  eo: epo
  es: spa
  et: est
  eu: eus
  fa: fas
  fi: fin
  fo: fao
  fr: fra
  fy: fry
  ga: gle
  gd: gla
  gl: glg
  gn: grn
  gu: guj
  gv: glv
  hi: hin
  hmn: UNK  # TODO
  hr: hrv
  ht: hat
  hu: hun
  hy: hye
  ia: ina
  id: ind
  ie: ile
  is: isl
  it: ita
  iu: UNK  # Eskimo–Aleut
  iw: heb
  ja: jpn
  jw: jav
  ka: kat
  kk: kaz
  km: khm
  kn: kan
  ko: kor
  ku: kur
  ky: kir
  la: lat
  lb: ltz
  lg: lug
  lif: lim
  ln: lin
  lo: lao
  lt: lit
  lv: lav
  mg: mlg
  mi: mri
  mk: mkd
  ml: mal
  mn: mon
  mr: mar
  ms: msa
  mt: mlt
  my: mya
  ne: nep
  new: new
  nl: nld
  nn: nno
  'no': nob
  nso: nso
  ny: UNK  # Chichewa, Chewa, Nyanja
  oc: oci
  or: ori
  os: oss
  pa: pan
  pam: pam
  pl: pol
  ps: pus
  pt: por
  qu: que
  rm: roh
  ro: ron
  ru: rus
  rw: kin
  sa: san
  sco: sco
  sd: snd
  si: sin
  sk: slk
  sl: slv
  sn: sna
  so: som
  sq: sqi
  sr: srp
  st: UNK  # Southern Sotho
  su: sun
  sv: swe
  sw: swa
  syr: UNK  # TODO
  ta: tam
  te: tel
  tg: tgk
  th: tha
  tk: tuk
  tl: tgl
  tn: tsn
  to: ton
  tr: tur
  tt: tat
  ug: uig
  uk: ukr
  un: UNK  # Unknown
  ur: urd
  uz: uzb
  vi: vie
  vo: vol
  war: war
  wo: wol
  xh: xho
  xx-Arab: ara
  xx-Armn: hye
  xx-Beng: ben
  xx-Copt: UNK  # X_Coptic
  xx-Geor: kat
  xx-Goth: UNK  # X_Gothic
  xx-Grek: ell
  xx-Gujr: guj
  xx-Hebr: heb
  xx-Java: jav
  xx-Khmr: khm
  xx-Knda: kan
  xx-Laoo: lao
  xx-Latn: lat
  xx-Mlym: msa
  xx-Mong: mon
  xx-Orya: ori
  xx-Sinh: sin
  xx-Sund: sun
  xx-Taml: tam
  xx-Telu: tel
  xx-Tfng: UNK  # X_Tifinagh
  xx-Tglg: tgl
  xx-Thai: tha
  xx-Tibt: bod
  xx-Yiii: UNK  # X_Yi
  yi: yid
  yo: yor
  zh: zho
  zh-Hant: lzh
