name: langdetect
mapping:
  af: afr
  ar: ara
  bg: bul
  bn: ben
  ca: cat
  cs: ces
  cy: cym
  da: dan
  de: deu
  el: ell
  en: eng
  es: spa
  et: est
  fa: fas
  fi: fin
  fr: fra
  gu: guj
  he: heb
  hi: hin
  hr: hrv
  hu: hun
  id: ind
  it: ita
  ja: jpn
  kn: kan
  ko: kor
  lt: lit
  lv: lav
  mk: mkd
  ml: mal
  mr: mar
  ne: nep
  nl: nld
  "no": nob
  pa: pan
  pl: pol
  pt: por
  ro: ron
  ru: rus
  sk: slk
  sl: slv
  so: som
  sq: sqi
  sv: swe
  sw: swa
  ta: tam
  te: tel
  th: tha
  tl: tgl
  tr: tur
  uk: ukr
  ur: urd
  vi: vie
  zh-cn: zho
  zh-tw: lzh
