name: textcat
mapping:
  abn: unk  # Unknown to WiLI!
  ace: ace
  ach: unk  # Unknown to WiLI!
  afr: afr
  agr: unk  # Unknown to WiLI!
  aka: unk  # Unknown to WiLI!
  als: sqi  # Unknown to WiLI!
  amh: amh
  ami: unk  # Unknown to WiLI!
  amr: unk  # Unknown to WiLI!
  ang: ang
  arb: ara  # Unknown to WiLI!
  arg: arg
  asm: asm
  ast: ast
  ava: ava
  ayr: aym  # Unknown to WiLI!
  azj: aze  # Unknown to WiLI!
  bak: bak
  bam: unk  # Unknown to WiLI!
  ban: unk  # Unknown to WiLI!
  bar: bar
  bba: unk  # Unknown to WiLI!
  bcc: unk  # Unknown to WiLI!
  bcl: bcl
  bel: bel
  ben: ben
  bis: unk  # Unknown to WiLI!
  bod: bod
  bos: bos
  bre: bre
  buc: unk  # Unknown to WiLI!
  bul: bul
  bxr: bxr
  byv: unk  # Unknown to WiLI!
  cat: cat
  cbr: unk  # Unknown to WiLI!
  ceb: ceb
  ces: ces
  cha: unk  # Unknown to WiLI!
  chv: chv
  cmn: cdo  # Unknown to WiLI!
  cnh: unk  # Unknown to WiLI!
  cor: cor
  cos: cos
  crs: unk  # Unknown to WiLI!
  csa: unk  # Unknown to WiLI!
  csb: csb
  cym: cym
  dan: dan
  ddn: unk  # Unknown to WiLI!
  deu: deu
  dhv: unk  # Unknown to WiLI!
  diq: diq
  dyu: unk  # Unknown to WiLI!
  dzo: bod  # Unknown to WiLI!
  ell: ell
  emk: unk  # Unknown to WiLI!
  eml: unk  # Unknown to WiLI!
  'eng ': eng
  eng: eng
  epo: epo
  est: est
  eus: eus
  ewe: unk  # Unknown to WiLI!
  fao: fao
  fij: unk  # Unknown to WiLI!
  fin: fin
  fra: fra
  fri: wuu  # Unknown to WiLI!
  frp: frp
  frr: unk  # Unknown to WiLI!
  fub: unk  # Unknown to WiLI!
  fud: unk  # Unknown to WiLI!
  fur: fur
  gag: gag
  gaz: unk  # Unknown to WiLI!
  gjn: unk  # Unknown to WiLI!
  gkn: unk  # Unknown to WiLI!
  gla: gla
  gle: gle
  glg: glg
  glv: glv
  got: unk  # Unknown to WiLI!
  gsc: unk  # Unknown to WiLI!
  gsw: gsw
  gug: grn  # Unknown to WiLI!
  guj: guj
  guw: lzh  # Unknown to WiLI!
  hat: hat
  hau: hau
  haw: unk  # Unknown to WiLI!
  heb: heb
  hil: ilo  # Unknown to WiLI!
  hin: hin
  hmo: unk  # Unknown to WiLI!
  hne: unk  # Unknown to WiLI!
  hrv: hrv
  hsb: dsb  # Unknown to WiLI!
  hun: hun
  hye: hye
  ibo: ibo
  ilo: ilo
  ina: ina
  ind: ind
  isl: isl
  ita: ita
  ivv: unk  # Unknown to WiLI!
  jav: jav
  kab: kab
  kal: unk  # Unknown to WiLI!
  kan: kan
  kat: kat
  kaz: kaz
  kbd: kbd
  khk: mon  # Unknown to WiLI!
  khm: khm
  kin: kin
  kir: kir
  kjh: unk  # Unknown to WiLI!
  kmr: kur  # Unknown to WiLI!
  knc: unk  # Unknown to WiLI!
  knn: unk  # Unknown to WiLI!
  kpv: unk  # Unknown to WiLI!
  krc: krc
  kri: unk  # Unknown to WiLI!
  ksh: ksh
  lad: lad
  lao: lao
  lat: lat
  lav: lav
  lin: lin
  lit: lit
  lld: unk  # Unknown to WiLI!
  lmo: lmo
  lms: unk  # Unknown to WiLI!
  lnc: oci  # Unknown to WiLI!
  loz: unk  # Unknown to WiLI!
  ltz: ltz
  lua: unk  # Unknown to WiLI!
  lug: lug
  lus: hak  # Unknown to WiLI!
  mal: mal
  mcd: unk  # Unknown to WiLI!
  mfe: lzh  # Unknown to WiLI!
  mho: unk  # Unknown to WiLI!
  mic: unk  # Unknown to WiLI!
  min: min
  mkd: mkd
  mlt: mlt
  mly: msa  # Unknown to WiLI!
  mri: mri
  mrj: mrj
  mus: unk  # Unknown to WiLI!
  mya: mya
  nap: nap
  naq: unk  # Unknown to WiLI!
  nav: nav
  nbl: unk  # Unknown to WiLI!
  nde: unk  # Unknown to WiLI!
  nds: nds
  nia: unk  # Unknown to WiLI!
  nld: nld
  nmf: sin  # Unknown to WiLI!
  nno: nno
  nob: nob
  nso: nso
  nya: unk  # Unknown to WiLI!
  nyk: unk  # Unknown to WiLI!
  ojw: unk  # Unknown to WiLI!
  ood: oci  # Unknown to WiLI!
  ori: ori
  oss: oss
  pam: pam
  pan: pan
  pap: pap
  pau: unk  # Unknown to WiLI!
  pbb: unk  # Unknown to WiLI!
  pbu: pus  # Unknown to WiLI!
  pcm: zho  # Unknown to WiLI!
  pdc: pdc
  pes: fas  # Map to best
  pih: unk  # Unknown to WiLI!
  pis: unk  # Unknown to WiLI!
  plt: mlg  # Unknown to WiLI!
  pms: unk  # Unknown to WiLI!
  pol: pol
  pon: unk  # Unknown to WiLI!
  por: por
  prq: zh-yue  # Unknown to WiLI!
  prs: unk  # Unknown to WiLI!
  prv: unk  # Unknown to WiLI!
  quh: que  # Unknown to WiLI!
  rar: unk  # Unknown to WiLI!
  rnd: unk  # Unknown to WiLI!
  roh: roh
  ron: ron
  rup: rup
  rus: rus
  scn: scn
  sco: sco
  slk: slk
  slv: slv
  sme: sme
  sna: sna
  snd: snd
  som: som
  sot: tsn  # Unknown to WiLI!
  spa: spa
  src: srd  # Unknown to WiLI!
  srm: unk  # Unknown to WiLI!
  srp: srp
  srr: unk  # Unknown to WiLI!
  ssw: jpn  # Unknown to WiLI!
  sum: unk  # Unknown to WiLI!
  sun: sun
  sus: unk  # Unknown to WiLI!
  swb: unk  # Unknown to WiLI!
  swe: swe
  swh: swa  # Unknown to WiLI!
  tam: tam
  tat: tat
  tel: tel
  teo: unk  # Unknown to WiLI!
  tet: tet
  tgk: tgk
  tgl: tgl
  tha: tha
  tig: unk  # Unknown to WiLI!
  ton: ton
  tos: unk  # Unknown to WiLI!
  tsc: unk  # Unknown to WiLI!
  tsn: tsn
  tso: unk  # Unknown to WiLI!
  tuk: tuk
  tur: tur
  tvl: unk  # Unknown to WiLI!
  tzc: unk  # Unknown to WiLI!
  tzm: kab  # Unknown to WiLI!
  udm: udm
  uig: uig
  ukr: ukr
  umb: unk  # Unknown to WiLI!
  urd: urd
  uzn: unk  # Unknown to WiLI!
  vec: vec
  ven: unk  # Unknown to WiLI!
  vie: vie
  vls: vls
  wol: wol
  xho: xho
  yaf: unk  # Unknown to WiLI!
  ydd: yid  # Unknown to WiLI!
  yor: yor
  zea: zea
  zul: xho  # Unknown to WiLI!
