parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

    pipeline:
      serviceResolvers:

services:
  databricksbundle.dbutils.DatabricksConnectDbUtilsFactory:

  databricksbundle.dbutils.DatabricksDbUtilsFactory:

  databricksbundle.dbutils.AutodetectionDbUtilsFactory:

  databricksbundle.dbutils.DbUtilsWrapper:
    factory: ['@databricksbundle.dbutils.AutodetectionDbUtilsFactory', 'create']

  databricksbundle.pipeline.function.ServiceResolver:
    arguments:
      - '%databricksbundle.pipeline.serviceResolvers%'

  databricksbundle.pipeline.function.ServicesResolver:
