
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-22T03:29:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "129c2c1379c08d0f223a8dd4062038f1182b7d47",
 "version": "0.0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
