# Generated by Django 2.1.7 on 2020-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_cartao_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cartao_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
