[tool.poetry]
name = "gino-enum-tables"
packages = [
    { include = "enumtables" }
]
version = "1.0.7"
description = "Support for storing enum values in a table instead of a type"
authors = ["Gazorby <gazorby@pm.me>", "Nathan/Eilisha Shiraini <neshiraini@heptacle.fr>"]
keywords = ["enum", "table", "type", "orm", "sqlalchemy", "python3"]
license = "Apache-2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "*"
sqlalchemy = "^1.3.18"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
