[tool.poetry]
name = "klusterinfo"
version = "0.1.0"
description = ""
authors = ["Steinn Eldjárn Sigurðarson <steinnes@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pykubeks = "0.1.0"
click = "^7.0"
pint = "^0.9.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
[tool.poetry.scripts]
klusterinfo = 'klusterinfo:cli'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

