[tool.poetry]
name = "clean-cybersource-rest-client-python"
version = "0.0.21"
description = ""
authors = ["Maximiliano Opitz <maximiliano@cornershopapp.com>"]
packages = [
    { include = "CyberSource" },
    { include = "authenticationsdk" },
]

[tool.poetry.dependencies]
python = "^3.7"
certifi = "2019.9.11"
six = "^1.12.0"
python_dateutil = "2.5.3"
setuptools = "21.0.0"
urllib3 = "1.15.1"
PyJWT = "1.6.4"
pyopenssl = "17.5.0"
pycryptodome = "3.9.8"

[tool.poetry.dev-dependencies]
coverage = "4.0.3"
nose = "1.3.7"
pluggy = "0.3.1"
py = "1.4.31"
randomize = "0.13"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"