[tool.poetry]
name = "pypi-semantic"
version = "0.1.0"
description = ""
authors = ["Matyi <mmatyi@caesar.elte.hu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.semantic_release]
version_variable = pypi_semantic/__init__.py:__version__