language: python
python:
  - "3.6"

install:
  - make install
  - pip install -U pytest pytest-cov codecov

script:
  - make test-cov

after_success:
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "..."
  on:
    tags: true
