[black]
args = ["--check"]
help = "Code formatter for python."
fast = true
test = true
strict = true

[black.format]
clear_args = true

[flake8]
args = ["--max-line-length=88", "--ignore=E203"]
help = "Code style checker for python."
fast = true
test = true
strict = true

[autoflake]
args = [
    "--in-place",
    "--recursive",
    "--expand-star-imports",
    "--remove-all-unused-imports"
]
help = "Remove unused imports and variables"
format = true
standard = false

[isort]
args = [
    "--profile=black",
    "--check-only"
]
help = "Tool for sorting and cleaning python imports."
fast = true
test = true
strict = true

[isort.format]
args = [
    "--profile=black"
]

[mypy]
args = ["--ignore-missing-imports"]
help = "Validate types using mypy."
test = true

[mypy.strict]
add_args = ["--strict"]

[pylint]
args = ["--ignore-imports=y", "--disable=bad-continuation"]
help = "Python code linter"
strict = true

[pylint.test]
add_args = [
    "--disable=C0103,C0114,C0115,C0116,C0203,C0204,C0330,C0411",
    "--disable=E0401,E0611,E1101,E1120,E1130,E1139",
    "--disable=R0801,R0902,R0903,R0904,R0913",
    "--disable=W0201,W0613,W0621"]

[bandit]
args = ["-r"]
help = "Python security checks tool."
strict = true

[bandit.test]
add_args = ["--skip=B101"]

[pydocstyle]
args = ["--ignore=D203,D212,D400,D401"]
help = "Tool for python docstring style enforcing"
test = false
strict = true