# Generated by Django 2.1.7 on 2020-07-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_auto_20200713_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True},
        ),
    ]
