[tool.poetry]
name = "swtor-settings-updater"
version = "0.0.4"
description = "Star Wars: The Old Republic Settings Updater"
readme = "README.md"
homepage = "https://github.com/ion1/swtor-settings-updater"
authors = ["Johan Kiviniemi <devel@johan.kiviniemi.name>"]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.8"
atomicwrites = "^1.4.0"
regex = ">=2020.7.14"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.782"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
tox = "^3.18"

flake8 = "^3.8.3"
flake8-bugbear = "^20.1.4"
flake8-colors = "^0.1.6"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
flake8-typing-imports = "^1.9.0"
pep8-naming = "^0.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
