language: python

dist: xenial

matrix:
  fast_finish: true
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9-dev"
  allow_failures:
    - python: "3.9-dev"

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - source $HOME/.cargo/env
  - export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB:$HOME/rust/lib"
  - pip install -e .

script:
  - cd example_tomlgen
  - python setup.py tomlgen_rust -w build
  - cd ..
  - cd html-py-ever
  - pip install -r requirements-dev.txt
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then cd test && pytest && cd ..; fi
  - cd ..
  - cd examples/
  # PEP517 build isolation means we don't use the setuptools-rust locally,
  # instead it installs from PyPI!
  - pip install -U pip
  - pip install --no-use-pep517 -e rust_with_cffi/
  - pytest rust_with_cffi/tests.py
