language: python

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

stages:
- test
- name: deploy
  if: repo = ESSS/pytest-replay AND tag IS present

jobs:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.7
      env: TOX_ENV=linting
    - stage: deploy
      python: '3.7'
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        skip_upload_docs: true
        distributions: sdist bdist_wheel
        password:
          secure: ZNzR9+tx8BaFtz1ouRD1gy1f8mU6EgmtGicG3n2y8cydVEfCOFJSjvHKVFvv3J6/mjahd2EPu4+AFoq1jq33/z+v+5cHn/7CGeAfbrBbBY8879hawIyZt3WABVwSwHVU6MMQFwRfoWlIeDldUoeMXXVItoiZ83RNstPseBS8GeHpwPUDiYO6eDopTuiWJOH5ljDWSQFnlIJ7FtW2DVMGakAoKFJJ8wl5XoPCEULnxBOXgc6IrI/wYsVOy+u6O0JVPkdAHWk/byL/sKHD7P0UexHJej60ZkTOLcMUkF6WurwkgACOj0qapa2meRy4otAD4rXNnZDnFtExiKYN9SyUIh/isuElMcC/mUwy43CPfUWCGMj9jM7GMJ0i38AfML4mZOEMH8M/szDqRnoafa0Fw4F0pYfaig3dGbQGQPg/Wn8K7gwClgB/IxiMJCoAoiDOr7NRrp6AH6dVhJd9IPU70lxoziuRuvNOEivBPrdJCXge7tzxioHXd8s9iSTZxcKSyLyajIhwIgbySc2Z03L9POoiQsHpxSQ42bM4Vt7N0C/f7iw6Xxuwjn023iDGxw32aFABfDIor4RYXIBzAZFlQNj6qSRddsVhfZUs+Cf31Pko7CvysOWHaYN5Fp2OiP/EqiTAB+Ab5WUGyPsyjU4EsL8/+TldqlyqewBHPwqpHnY=
        on:
          tags: true
          repo: ESSS/pytest-replay
