# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
    - PYTHON: "C:\\Python37"
      TOXENV: "py37"
    - PYTHON: "C:\\Python38"
      TOXENV: "py38"

install:
  - "%PYTHON%/Scripts/pip install tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

skip_tags: true
