# Generated by Django 2.2.7 on 2020-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_load_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
